package com.stasdoto.airdefense.vehicle;

import com.stasdoto.airdefense.vehicle.VehicleGeometry.Geometry;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Rail;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Seat;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Wheel;

/** GENERATED by tools/models/build.py - do not edit. Geometry of the generated vehicles. */
@SuppressWarnings("unused")
public final class GenGeometry {
	private GenGeometry() {
	}

	public static final Geometry P18 = new Geometry("p18", 7.85F, 2.5F, 7.2F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.27F, 1.55F), new Seat("gunner", 0.5F, 1.27F, 1.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 144);

	public static final Geometry ST68 = new Geometry("st68", 13.54F, 2.6F, 5.1F, 7F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.6F, 4F), new Seat("gunner", 0.55F, 1.6F, 4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.68F, true), new Wheel("wheel_1_r", 0.68F, true), new Wheel("wheel_2_l", 0.68F, false), new Wheel("wheel_2_r", 0.68F, false), new Wheel("wheel_3_l", 0.68F, false), new Wheel("wheel_3_r", 0.68F, false), new Wheel("trailer_1_l", 0.6F, false), new Wheel("trailer_1_r", 0.6F, false), new Wheel("trailer_2_l", 0.6F, false), new Wheel("trailer_2_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 17F,
			1024, 208);

	public static final Geometry TRML4D = new Geometry("trml4d", 8.79F, 2.55F, 5.2F, 5F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.75F, 3.2F), new Seat("gunner", 0.6F, 1.75F, 3.2F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 160);

	public static final Geometry SENTINEL = new Geometry("sentinel", 9.58F, 2.2F, 3.6F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.45F, 0.72F, 2.1F), new Seat("gunner", 0.45F, 0.72F, 2.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.46F, true), new Wheel("wheel_1_r", 0.46F, true), new Wheel("wheel_2_l", 0.46F, false), new Wheel("wheel_2_r", 0.46F, false), new Wheel("trailer_l", 0.46F, false), new Wheel("trailer_r", 0.46F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 12F,
			1024, 96);

	public static final Geometry MPQ65 = new Geometry("mpq65", 13.04F, 2.5F, 3.9F, 7.5F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.614F, 5.6F), new Seat("gunner", 0.55F, 1.614F, 5.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.66F, true), new Wheel("wheel_1_r", 0.66F, true), new Wheel("wheel_2_l", 0.66F, true), new Wheel("wheel_2_r", 0.66F, true), new Wheel("rear_1_l", 0.66F, false), new Wheel("rear_1_r", 0.66F, false), new Wheel("rear_2_l", 0.66F, false), new Wheel("rear_2_r", 0.66F, false), new Wheel("trailer_1_l", 0.58F, false), new Wheel("trailer_1_r", 0.58F, false), new Wheel("trailer_2_l", 0.58F, false), new Wheel("trailer_2_r", 0.58F, false)},
			null, new float[]{0F, 0F, 0F}, "array", new float[]{0F, 3.4F, -5.6F},
			72F, 0F, new Rail[]{}, null, new String[]{}, 17F,
			1024, 208);

	public static final Geometry KUPOL = new Geometry("kupol", 9.18F, 3.25F, 5.9F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1.6F, 3.4F), new Seat("gunner", 0.6F, 1.6F, 3.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.33F, false), new Wheel("road_1_l", 0.33F, false), new Wheel("road_2_l", 0.33F, false), new Wheel("road_3_l", 0.33F, false), new Wheel("road_4_l", 0.33F, false), new Wheel("road_5_l", 0.33F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.33F, false), new Wheel("road_1_r", 0.33F, false), new Wheel("road_2_r", 0.33F, false), new Wheel("road_3_r", 0.33F, false), new Wheel("road_4_r", 0.33F, false), new Wheel("road_5_r", 0.33F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 352);

	public static final Geometry ELM2084 = new Geometry("elm2084", 9.39F, 2.55F, 5.55F, 5.2F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.75F, 3.5F), new Seat("gunner", 0.6F, 1.75F, 3.5F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, true), new Wheel("wheel_2_r", 0.6F, true), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false), new Wheel("wheel_4_l", 0.6F, false), new Wheel("wheel_4_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 15F,
			1024, 176);

	public static final Geometry PANTSIR = new Geometry("pantsir", 9.99F, 2.55F, 4.45F, 6.3F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.514F, 3.8F), new Seat("gunner", 0.6F, 1.514F, 3.8F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, true), new Wheel("wheel_2_r", 0.62F, true), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false), new Wheel("wheel_4_l", 0.62F, false), new Wheel("wheel_4_r", 0.62F, false)},
			"turret", new float[]{0F, 1.8F, -2.4F}, "weapons", new float[]{0F, 0.75F, -0.3F},
			15F, 0F, new Rail[]{new Rail("can_0", -1.79F, -0.17F, 2.3F), new Rail("can_1", -1.55F, -0.17F, 2.3F), new Rail("can_2", -1.31F, -0.17F, 2.3F), new Rail("can_3", -1.79F, 0.21F, 2.3F), new Rail("can_4", -1.55F, 0.21F, 2.3F), new Rail("can_5", -1.31F, 0.21F, 2.3F), new Rail("can_6", 1.31F, -0.17F, 2.3F), new Rail("can_7", 1.55F, -0.17F, 2.3F), new Rail("can_8", 1.79F, -0.17F, 2.3F), new Rail("can_9", 1.31F, 0.21F, 2.3F), new Rail("can_10", 1.55F, 0.21F, 2.3F), new Rail("can_11", 1.79F, 0.21F, 2.3F), new Rail("barrel_l", -1.55F, -0.5F, 3F), new Rail("barrel_r", 1.55F, -0.5F, 3F)}, "search", new String[]{}, 14F,
			1024, 240);

	public static final Geometry TOR = new Geometry("tor", 7.63F, 3.3F, 4.3F, 0F, true,
			new Seat[]{new Seat("driver", -0.75F, 1.3F, 3F), new Seat("gunner", 0F, 2.6F, 0.2F)},
			new Wheel[]{new Wheel("road_0_l", 0.32F, false), new Wheel("road_1_l", 0.32F, false), new Wheel("road_2_l", 0.32F, false), new Wheel("road_3_l", 0.32F, false), new Wheel("road_4_l", 0.32F, false), new Wheel("road_5_l", 0.32F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.32F, false), new Wheel("road_1_r", 0.32F, false), new Wheel("road_2_r", 0.32F, false), new Wheel("road_3_r", 0.32F, false), new Wheel("road_4_r", 0.32F, false), new Wheel("road_5_r", 0.32F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.8F, -0.4F}, "vls", new float[]{0F, 1.2F, 0F},
			90F, 90F, new Rail[]{new Rail("cell_0", -0.6F, 0.9F, 0.6F), new Rail("cell_1", -0.2F, 0.9F, 0.6F), new Rail("cell_2", 0.2F, 0.9F, 0.6F), new Rail("cell_3", 0.6F, 0.9F, 0.6F), new Rail("cell_4", -0.6F, 0.45F, 0.6F), new Rail("cell_5", -0.2F, 0.45F, 0.6F), new Rail("cell_6", 0.2F, 0.45F, 0.6F), new Rail("cell_7", 0.6F, 0.45F, 0.6F)}, "search", new String[]{}, 12F,
			1024, 256);

	public static final Geometry BUK = new Geometry("buk", 9.23F, 3.25F, 4.31F, 0F, true,
			new Seat[]{new Seat("driver", -0.9F, 1.5F, 3.8F), new Seat("gunner", 0.6F, 2.4F, 0.3F)},
			new Wheel[]{new Wheel("road_0_l", 0.33F, false), new Wheel("road_1_l", 0.33F, false), new Wheel("road_2_l", 0.33F, false), new Wheel("road_3_l", 0.33F, false), new Wheel("road_4_l", 0.33F, false), new Wheel("road_5_l", 0.33F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.33F, false), new Wheel("road_1_r", 0.33F, false), new Wheel("road_2_r", 0.33F, false), new Wheel("road_3_r", 0.33F, false), new Wheel("road_4_r", 0.33F, false), new Wheel("road_5_r", 0.33F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.85F, -0.6F}, "launcher", new float[]{0F, 1.15F, -1.6F},
			25F, 0F, new Rail[]{new Rail("missile_0", -0.55F, 0.2F, 5.5F), new Rail("missile_1", 0.55F, 0.2F, 5.5F), new Rail("missile_2", -0.55F, 0.75F, 5.5F), new Rail("missile_3", 0.55F, 0.75F, 5.5F)}, null, new String[]{}, 14F,
			1024, 384);

	public static final Geometry S300 = new Geometry("s300", 13.18F, 3.05F, 4.24F, 7F, false,
			new Seat[]{new Seat("driver", -1.05F, 1.452F, 5.4F), new Seat("gunner", 1.05F, 1.452F, 5.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.78F, true), new Wheel("wheel_1_r", 0.78F, true), new Wheel("wheel_2_l", 0.78F, true), new Wheel("wheel_2_r", 0.78F, true), new Wheel("wheel_3_l", 0.78F, false), new Wheel("wheel_3_r", 0.78F, false), new Wheel("wheel_4_l", 0.78F, false), new Wheel("wheel_4_r", 0.78F, false)},
			null, new float[]{0F, 0F, 0F}, "erector", new float[]{0F, 2F, -6F},
			90F, 0F, new Rail[]{new Rail("can_0", -0.56F, 0.62F, 7.6F), new Rail("can_1", 0.56F, 0.62F, 7.6F), new Rail("can_2", -0.56F, 1.72F, 7.6F), new Rail("can_3", 0.56F, 1.72F, 7.6F)}, null, new String[]{}, 17F,
			1024, 384);

	public static final Geometry OSA = new Geometry("osa", 9.38F, 2.75F, 3.75F, 4F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.55F, 2.7F), new Seat("gunner", 0.5F, 1.55F, 2.7F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			"turret", new float[]{0F, 1.85F, -0.9F}, "launcher", new float[]{0F, 0.55F, -0.4F},
			25F, 0F, new Rail[]{new Rail("missile_0", -1.5F, -0.35F, 2.05F), new Rail("missile_1", -1.5F, 0.07F, 2.05F), new Rail("missile_2", -1.5F, 0.49F, 2.05F), new Rail("missile_3", 1.5F, -0.35F, 2.05F), new Rail("missile_4", 1.5F, 0.07F, 2.05F), new Rail("missile_5", 1.5F, 0.49F, 2.05F)}, "search", new String[]{}, 12F,
			1024, 176);

	public static final Geometry STRELA10 = new Geometry("strela10", 6.63F, 2.85F, 2.57F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1.2F, 2.4F), new Seat("gunner", 0F, 2F, -0.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.27F, false), new Wheel("road_1_l", 0.27F, false), new Wheel("road_2_l", 0.27F, false), new Wheel("road_3_l", 0.27F, false), new Wheel("road_4_l", 0.27F, false), new Wheel("road_5_l", 0.27F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.27F, false), new Wheel("road_1_r", 0.27F, false), new Wheel("road_2_r", 0.27F, false), new Wheel("road_3_r", 0.27F, false), new Wheel("road_4_r", 0.27F, false), new Wheel("road_5_r", 0.27F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.65F, -0.4F}, "launcher", new float[]{0F, 0.65F, 0F},
			30F, 0F, new Rail[]{new Rail("can_0", -1F, 0.15F, 1.3F), new Rail("can_1", -1.28F, 0.15F, 1.3F), new Rail("can_2", 1F, 0.15F, 1.3F), new Rail("can_3", 1.28F, 0.15F, 1.3F)}, null, new String[]{}, 11F,
			1024, 208);

	public static final Geometry SHILKA = new Geometry("shilka", 6.63F, 3.1F, 3.75F, 0F, true,
			new Seat[]{new Seat("driver", -0.7F, 1.3F, 2.5F), new Seat("gunner", 0F, 2.3F, -0.3F)},
			new Wheel[]{new Wheel("road_0_l", 0.3F, false), new Wheel("road_1_l", 0.3F, false), new Wheel("road_2_l", 0.3F, false), new Wheel("road_3_l", 0.3F, false), new Wheel("road_4_l", 0.3F, false), new Wheel("road_5_l", 0.3F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.3F, false), new Wheel("road_1_r", 0.3F, false), new Wheel("road_2_r", 0.3F, false), new Wheel("road_3_r", 0.3F, false), new Wheel("road_4_r", 0.3F, false), new Wheel("road_5_r", 0.3F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.7F, -0.3F}, "guns", new float[]{0F, 0.35F, 1.3F},
			0F, 0F, new Rail[]{new Rail("barrel_l", -0.55F, 0F, 2.1F), new Rail("barrel_r", 0.55F, 0F, 2.1F)}, "radar", new String[]{}, 11F,
			1024, 208);

	public static final Geometry TUNGUSKA = new Geometry("tunguska", 7.83F, 3.25F, 3.9F, 0F, true,
			new Seat[]{new Seat("driver", -0.75F, 1.3F, 3F), new Seat("gunner", 0F, 2.6F, -0.5F)},
			new Wheel[]{new Wheel("road_0_l", 0.32F, false), new Wheel("road_1_l", 0.32F, false), new Wheel("road_2_l", 0.32F, false), new Wheel("road_3_l", 0.32F, false), new Wheel("road_4_l", 0.32F, false), new Wheel("road_5_l", 0.32F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.32F, false), new Wheel("road_1_r", 0.32F, false), new Wheel("road_2_r", 0.32F, false), new Wheel("road_3_r", 0.32F, false), new Wheel("road_4_r", 0.32F, false), new Wheel("road_5_r", 0.32F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.8F, -0.5F}, "weapons", new float[]{0F, 0.7F, 0F},
			12F, 0F, new Rail[]{new Rail("can_0", -1.89F, 0.1F, 1.6F), new Rail("can_1", -1.61F, 0.1F, 1.6F), new Rail("can_2", -1.89F, 0.4F, 1.6F), new Rail("can_3", -1.61F, 0.4F, 1.6F), new Rail("barrel_l", -1.75F, -0.3F, 2.5F), new Rail("can_4", 1.61F, 0.1F, 1.6F), new Rail("can_5", 1.89F, 0.1F, 1.6F), new Rail("can_6", 1.61F, 0.4F, 1.6F), new Rail("can_7", 1.89F, 0.4F, 1.6F), new Rail("barrel_r", 1.75F, -0.3F, 2.5F)}, "search", new String[]{}, 12F,
			1024, 272);

	public static final Geometry SAMPT = new Geometry("sampt", 10.94F, 2.55F, 3.05F, 6.5F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.564F, 4.2F), new Seat("gunner", 0.6F, 1.564F, 4.2F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, true), new Wheel("wheel_2_r", 0.6F, true), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false), new Wheel("wheel_4_l", 0.6F, false), new Wheel("wheel_4_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, "launcher", new float[]{0F, 1.75F, -5.3F},
			90F, 0F, new Rail[]{new Rail("can_0", -0.87F, 0.3F, 6.5F), new Rail("can_1", -0.29F, 0.3F, 6.5F), new Rail("can_2", 0.29F, 0.3F, 6.5F), new Rail("can_3", 0.87F, 0.3F, 6.5F), new Rail("can_4", -0.87F, 0.9F, 6.5F), new Rail("can_5", -0.29F, 0.9F, 6.5F), new Rail("can_6", 0.29F, 0.9F, 6.5F), new Rail("can_7", 0.87F, 0.9F, 6.5F)}, null, new String[]{}, 15F,
			1024, 272);

	public static final Geometry AVENGER = new Geometry("avenger", 4.68F, 2.2F, 2.4F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.45F, 0.72F, 0F), new Seat("gunner", 0F, 1.6F, -1.5F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.46F, true), new Wheel("wheel_1_r", 0.46F, true), new Wheel("wheel_2_l", 0.46F, false), new Wheel("wheel_2_r", 0.46F, false)},
			"turret", new float[]{0F, 1.35F, -1.5F}, "pods", new float[]{0F, 0.65F, 0F},
			20F, 0F, new Rail[]{new Rail("pod_l", -1F, -0.3F, 1F), new Rail("pod_l", -1F, -0.1F, 1F), new Rail("pod_l", -1F, 0.1F, 1F), new Rail("pod_l", -1F, 0.3F, 1F), new Rail("pod_r", 1F, -0.3F, 1F), new Rail("pod_r", 1F, -0.1F, 1F), new Rail("pod_r", 1F, 0.1F, 1F), new Rail("pod_r", 1F, 0.3F, 1F)}, null, new String[]{}, 10F,
			1024, 80);

	public static final Geometry MFG = new Geometry("mfg", 5.46F, 1.85F, 1.9F, 3.1F, false,
			new Seat[]{new Seat("driver", -0.4F, 0.72F, 0.4F), new Seat("gunner", 0F, 1.1F, -2.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.4F, true), new Wheel("wheel_1_r", 0.4F, true), new Wheel("wheel_2_l", 0.4F, false), new Wheel("wheel_2_r", 0.4F, false)},
			"mount", new float[]{0F, 1F, -1.5F}, "gun", new float[]{0F, 0.8F, 0F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0.02F, 1.4F), new Rail("barrel_2", 0F, 0.02F, 1.4F)}, null, new String[]{}, 8F,
			1024, 48);

	public static final Geometry ZU23 = new Geometry("zu23", 7.04F, 2.5F, 2.9F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.414F, 2.4F), new Seat("gunner", 0F, 1.6F, -2.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			"mount", new float[]{0F, 1.2F, -1.4F}, "guns", new float[]{0F, 0.75F, 0F},
			0F, 0F, new Rail[]{new Rail("barrel_l", -0.22F, 0F, 2.3F), new Rail("barrel_r", 0.22F, 0F, 2.3F)}, null, new String[]{}, 10F,
			1024, 128);

	public static final Geometry IRON_DOME = new Geometry("iron_dome", 9.09F, 2.55F, 3.89F, 4.6F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.514F, 3.6F), new Seat("gunner", 0.6F, 1.514F, 3.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, "launcher", new float[]{0F, 1.75F, -4F},
			55F, 0F, new Rail[]{new Rail("cell_0", -0.69F, 0.4F, 5.8F), new Rail("cell_1", -0.23F, 0.4F, 5.8F), new Rail("cell_2", 0.23F, 0.4F, 5.8F), new Rail("cell_3", 0.69F, 0.4F, 5.8F), new Rail("cell_4", -0.69F, 0.73F, 5.8F), new Rail("cell_5", -0.23F, 0.73F, 5.8F), new Rail("cell_6", 0.23F, 0.73F, 5.8F), new Rail("cell_7", 0.69F, 0.73F, 5.8F), new Rail("cell_8", -0.69F, 1.06F, 5.8F), new Rail("cell_9", -0.23F, 1.06F, 5.8F), new Rail("cell_10", 0.23F, 1.06F, 5.8F), new Rail("cell_11", 0.69F, 1.06F, 5.8F), new Rail("cell_12", -0.69F, 1.39F, 5.8F), new Rail("cell_13", -0.23F, 1.39F, 5.8F), new Rail("cell_14", 0.23F, 1.39F, 5.8F), new Rail("cell_15", 0.69F, 1.39F, 5.8F), new Rail("cell_16", -0.69F, 1.72F, 5.8F), new Rail("cell_17", -0.23F, 1.72F, 5.8F), new Rail("cell_18", 0.23F, 1.72F, 5.8F), new Rail("cell_19", 0.69F, 1.72F, 5.8F)}, null, new String[]{}, 13F,
			1024, 240);

	public static final Geometry T72 = new Geometry("t72", 10.82F, 3.6F, 5.75F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1F, 2.3F), new Seat("gunner", 0.6F, 2.2F, -0.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.55F, -0.3F}, "gun", new float[]{0F, 0.4F, 1.4F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.55F)}, null, new String[]{}, 10F,
			1024, 288);

	public static final Geometry T90 = new Geometry("t90", 10.9F, 3.78F, 5.5F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1F, 2.3F), new Seat("gunner", 0.6F, 2.2F, -0.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.55F, -0.3F}, "gun", new float[]{0F, 0.4F, 1.5F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.55F)}, null, new String[]{}, 10F,
			1024, 288);

	public static final Geometry LEOPARD2 = new Geometry("leopard2", 11.5F, 3.75F, 5.55F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1.05F, 2.6F), new Seat("gunner", 0.6F, 2.4F, -1F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("road_6_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("road_6_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.75F, -0.6F}, "gun", new float[]{0F, 0.4F, 1.8F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 6.35F)}, null, new String[]{}, 11F,
			1024, 304);

	public static final Geometry ABRAMS = new Geometry("abrams", 10.75F, 3.66F, 5.65F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1F, 2.9F), new Seat("gunner", 0.6F, 2.3F, -1.2F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("road_6_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("road_6_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.55F, -0.8F}, "gun", new float[]{0F, 0.45F, 2F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.35F)}, null, new String[]{}, 11F,
			1024, 304);

	public static final Geometry BMP2 = new Geometry("bmp2", 7.33F, 3.15F, 2.63F, 0F, true,
			new Seat[]{new Seat("driver", -0.7F, 1.15F, 2.3F), new Seat("gunner", 0F, 2.1F, -0.5F)},
			new Wheel[]{new Wheel("road_0_l", 0.32F, false), new Wheel("road_1_l", 0.32F, false), new Wheel("road_2_l", 0.32F, false), new Wheel("road_3_l", 0.32F, false), new Wheel("road_4_l", 0.32F, false), new Wheel("road_5_l", 0.32F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.32F, false), new Wheel("road_1_r", 0.32F, false), new Wheel("road_2_r", 0.32F, false), new Wheel("road_3_r", 0.32F, false), new Wheel("road_4_r", 0.32F, false), new Wheel("road_5_r", 0.32F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.75F, -0.2F}, "gun", new float[]{0F, 0.3F, 0.85F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 3.25F)}, null, new String[]{}, 10F,
			1024, 208);

	public static final Geometry BRADLEY = new Geometry("bradley", 6.83F, 3.6F, 3.1F, 0F, true,
			new Seat[]{new Seat("driver", -0.9F, 1.4F, 2F), new Seat("gunner", 0.35F, 2.5F, -0.7F)},
			new Wheel[]{new Wheel("road_0_l", 0.35F, false), new Wheel("road_1_l", 0.35F, false), new Wheel("road_2_l", 0.35F, false), new Wheel("road_3_l", 0.35F, false), new Wheel("road_4_l", 0.35F, false), new Wheel("road_5_l", 0.35F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.35F, false), new Wheel("road_1_r", 0.35F, false), new Wheel("road_2_r", 0.35F, false), new Wheel("road_3_r", 0.35F, false), new Wheel("road_4_r", 0.35F, false), new Wheel("road_5_r", 0.35F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0.35F, 2.15F, -0.3F}, "gun", new float[]{0F, 0.3F, 1F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 2.75F)}, null, new String[]{}, 10F,
			1024, 208);

	public static final Geometry BTR82 = new Geometry("btr82", 8.14F, 2.9F, 2.7F, 4.4F, false,
			new Seat[]{new Seat("driver", -0.5F, 0.77F, 2.2F), new Seat("gunner", 0F, 2.3F, 0.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, true), new Wheel("wheel_2_r", 0.6F, true), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false), new Wheel("wheel_4_l", 0.6F, false), new Wheel("wheel_4_r", 0.6F, false)},
			"turret", new float[]{0F, 2.15F, 0.6F}, "gun", new float[]{0F, 0.3F, 0.75F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 2.95F)}, null, new String[]{}, 10F,
			1024, 144);

	public static final Geometry BTR4 = new Geometry("btr4", 7.87F, 2.94F, 2.95F, 4.5F, false,
			new Seat[]{new Seat("driver", -0.6F, 0.87F, 2.9F), new Seat("gunner", 0F, 2.3F, -0.9F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, true), new Wheel("wheel_2_r", 0.62F, true), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false), new Wheel("wheel_4_l", 0.62F, false), new Wheel("wheel_4_r", 0.62F, false)},
			"turret", new float[]{0F, 2.1F, -0.6F}, "gun", new float[]{0.15F, 0.3F, 0.85F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 2.95F)}, null, new String[]{}, 10F,
			1024, 160);

	public static final Geometry M113 = new Geometry("m113", 4.92F, 2.69F, 2.6F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1.25F, 1.6F), new Seat("gunner", 0.3F, 2F, 0F)},
			new Wheel[]{new Wheel("road_0_l", 0.3F, false), new Wheel("road_1_l", 0.3F, false), new Wheel("road_2_l", 0.3F, false), new Wheel("road_3_l", 0.3F, false), new Wheel("road_4_l", 0.3F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.3F, false), new Wheel("road_1_r", 0.3F, false), new Wheel("road_2_r", 0.3F, false), new Wheel("road_3_r", 0.3F, false), new Wheel("road_4_r", 0.3F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0.3F, 1.95F, 0.3F}, "gun", new float[]{0F, 0.5F, 0.3F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.55F)}, null, new String[]{}, 9F,
			1024, 112);

	public static final Geometry MAXXPRO = new Geometry("maxxpro", 6.58F, 2.6F, 3.5F, 3.9F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.6F, 0.9F), new Seat("gunner", 0F, 2.6F, -1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false)},
			"turret", new float[]{0F, 2.9F, -0.6F}, "gun", new float[]{0F, 0.4F, 0.55F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.55F)}, null, new String[]{}, 10F,
			1024, 128);

	public static final Geometry KOZAK = new Geometry("kozak", 5.96F, 2.5F, 3F, 3.6F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.071F, 1F), new Seat("gunner", 0F, 2.2F, -1.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, false), new Wheel("wheel_2_r", 0.55F, false)},
			"turret", new float[]{0F, 2.45F, -0.8F}, "gun", new float[]{0F, 0.4F, 0.45F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.55F)}, null, new String[]{}, 9F,
			1024, 112);

	public static final Geometry GYURZA = new Geometry("gyurza", 23F, 4.8F, 7.3F, 0F, false,
			new Seat[]{new Seat("driver", -0.6F, 3.8F, 1.5F), new Seat("gunner", 0F, 2F, 5.9F)},
			new Wheel[]{},
			"turret", new float[]{0F, 1.6F, 6.5F}, "gun", new float[]{0F, 0.5F, 0.9F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 2.95F)}, null, new String[]{}, 18F,
			1024, 768);

	public static final Geometry RAPTOR = new Geometry("raptor", 16.9F, 4.1F, 4.8F, 0F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.752F, 1F), new Seat("gunner", 0F, 1.8F, 4.1F)},
			new Wheel[]{},
			"turret", new float[]{0F, 1.4F, 4.6F}, "gun", new float[]{0F, 0.4F, 0.6F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.95F)}, null, new String[]{}, 14F,
			1024, 384);

	public static final Geometry RHIB = new Geometry("rhib", 8.5F, 2.6F, 1.4F, 0F, false,
			new Seat[]{new Seat("driver", -0.3F, 0.4F, -0.8F), new Seat("gunner", 0F, 0.4F, 1.2F)},
			new Wheel[]{},
			"turret", new float[]{0F, 0.2F, 1.8F}, "gun", new float[]{0F, 1.05F, 0F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.45F)}, null, new String[]{}, 9F,
			1024, 128);

	public static final Geometry MI8 = new Geometry("mi8", 24.5625F, 2.5F, 5.8F, 0F, false,
			new Seat[]{new Seat("driver", -0.48F, 1.45F, 5.75F), new Seat("gunner", 0.48F, 1.45F, 5.75F), new Seat("passenger", -0.6F, 1.2F, 2.5F), new Seat("passenger", 0.6F, 1.2F, 2.5F), new Seat("passenger", -0.6F, 1.2F, 0.5F), new Seat("passenger", 0.6F, 1.2F, 0.5F)},
			new Wheel[]{new Wheel("gear_nose_a", 0.3F, false), new Wheel("gear_nose_b", 0.3F, false), new Wheel("gear_l", 0.42F, false), new Wheel("gear_r", 0.42F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "rotor", new String[]{}, 20F,
			1024, 352);

	public static final Geometry MI24 = new Geometry("mi24", 19.9375F, 2F, 5.65F, 0F, false,
			new Seat[]{new Seat("driver", 0F, 2.25F, 3.75F), new Seat("gunner", 0F, 1.62F, 5.55F)},
			new Wheel[]{new Wheel("gear_nose_a", 0.3F, false), new Wheel("gear_nose_b", 0.3F, false), new Wheel("gear_l", 0.4F, false), new Wheel("gear_r", 0.4F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "rotor", new String[]{}, 18F,
			1024, 304);

	public static final Geometry KA52 = new Geometry("ka52", 16.0667F, 2.2F, 4.79F, 0F, false,
			new Seat[]{new Seat("driver", -0.42F, 1.2F, 3.25F), new Seat("gunner", 0.42F, 1.2F, 3.25F)},
			new Wheel[]{new Wheel("gear_nose_a", 0.3F, false), new Wheel("gear_nose_b", 0.3F, false), new Wheel("gear_l", 0.38F, false), new Wheel("gear_r", 0.38F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "rotor", new String[]{}, 16F,
			1024, 256);

	public static final Geometry SU25 = new Geometry("su25", 15.925F, 2.6F, 5F, 0F, false,
			new Seat[]{new Seat("driver", 0F, 2.2F, 3.45F)},
			new Wheel[]{new Wheel("gear_nose", 0.33F, false), new Wheel("gear_l", 0.45F, false), new Wheel("gear_r", 0.45F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 18F,
			1024, 336);

	public static final Geometry F16 = new Geometry("f16", 15.6125F, 2.4F, 4.85F, 0F, false,
			new Seat[]{new Seat("driver", 0F, 1.98F, 3.55F)},
			new Wheel[]{new Wheel("gear_nose", 0.27F, false), new Wheel("gear_l", 0.36F, false), new Wheel("gear_r", 0.36F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 18F,
			1024, 288);

	public static final Geometry FUEL_TRUCK = new Geometry("fuel_truck", 7.36F, 2.5F, 3.15F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.27F, 1.55F), new Seat("gunner", 0.5F, 1.27F, 1.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 176);

	public static final Geometry SUPPLY_TRUCK = new Geometry("supply_truck", 7.44F, 2.5F, 3.3F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.27F, 1.55F), new Seat("gunner", 0.5F, 1.27F, 1.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 176);

	public static final Geometry FIRE_TRUCK = new Geometry("fire_truck", 7.62F, 2.5F, 3.26F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.55F, 2.6F), new Seat("gunner", 0.5F, 1.55F, 2.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, false), new Wheel("wheel_2_r", 0.55F, false), new Wheel("wheel_3_l", 0.55F, false), new Wheel("wheel_3_r", 0.55F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 160);

	public static final Geometry AMBULANCE = new Geometry("ambulance", 6.08F, 2.1F, 2.75F, 3.6F, false,
			new Seat[]{new Seat("driver", -0.5F, 0.783F, 1.4F), new Seat("gunner", 0.5F, 0.783F, 1.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.42F, true), new Wheel("wheel_1_r", 0.42F, true), new Wheel("wheel_2_l", 0.42F, false), new Wheel("wheel_2_r", 0.42F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 9F,
			1024, 112);

	public static final Geometry POLICE_CAR = new Geometry("police_car", 4.75F, 1.85F, 1.71F, 2.8F, false,
			new Seat[]{new Seat("driver", -0.4F, 0.57F, 0.1F), new Seat("gunner", 0.4F, 0.57F, 0.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.33F, true), new Wheel("wheel_1_r", 0.33F, true), new Wheel("wheel_2_l", 0.33F, false), new Wheel("wheel_2_r", 0.33F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 8F,
			1024, 96);

	public static final Geometry EMU_HEAD = new Geometry("emu_head", 21.2F, 3.31F, 4.4F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 1792);

	public static final Geometry EMU_CAR = new Geometry("emu_car", 21.2F, 3.31F, 5.3F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 1904);

	public static final Geometry LOCO = new Geometry("loco", 19.2F, 3.24F, 4.6F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 1200);

	public static final Geometry BOXCAR = new Geometry("boxcar", 15.2F, 3.28F, 4.1F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 576);

	public static final Geometry TANK_CAR = new Geometry("tank_car", 13.2F, 2.92F, 4.35F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 512);

	public static final Geometry GONDOLA = new Geometry("gondola", 14.2F, 3.22F, 3.6F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 640);

	public static final Geometry AIRLINER = new Geometry("airliner", 38.26F, 34.22F, 11.9F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 2448);

	public static final Geometry TURBOPROP = new Geometry("turboprop", 28.075F, 27F, 7.549F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 1440);

	public static final Geometry LORRY_BOX = new Geometry("lorry_box", 10.37F, 3.1F, 3.9F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 256);

	public static final Geometry LORRY_TANK = new Geometry("lorry_tank", 10.56F, 3.1F, 3.85F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 352);

	public static final Geometry TIPPER = new Geometry("tipper", 8.6F, 3.1F, 3.85F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 208);

	public static final Geometry TRACTOR = new Geometry("tractor", 5.72F, 3.6F, 2.92F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 48);

	public static final Geometry TOWER_CRANE = new Geometry("tower_crane", 59F, 4.43F, 47.8F, 0F, false,
			new Seat[]{},
			new Wheel[]{},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 368);

	public static final Geometry MSTA_S = new Geometry("msta_s", 13.05F, 3.58F, 3.25F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1F, 2.3F), new Seat("gunner", 0.8F, 2.75F, -1.25F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.6F, -0.6F}, "gun", new float[]{0F, 0.65F, 1.75F},
			45F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 8F)}, null, new String[]{}, 12F,
			1024, 288);

	public static final Geometry M109 = new Geometry("m109", 11.5F, 3.15F, 3.25F, 0F, true,
			new Seat[]{new Seat("driver", -0.85F, 1.25F, 2.3F), new Seat("gunner", 0.8F, 2.85F, -1.8F)},
			new Wheel[]{new Wheel("road_0_l", 0.33F, false), new Wheel("road_1_l", 0.33F, false), new Wheel("road_2_l", 0.33F, false), new Wheel("road_3_l", 0.33F, false), new Wheel("road_4_l", 0.33F, false), new Wheel("road_5_l", 0.33F, false), new Wheel("road_6_l", 0.33F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.33F, false), new Wheel("road_1_r", 0.33F, false), new Wheel("road_2_r", 0.33F, false), new Wheel("road_3_r", 0.33F, false), new Wheel("road_4_r", 0.33F, false), new Wheel("road_5_r", 0.33F, false), new Wheel("road_6_r", 0.33F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.9F, -1.2F}, "gun", new float[]{0F, 0.4F, 1.6F},
			45F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 6.95F)}, null, new String[]{}, 11F,
			1024, 208);

	public static final Geometry BM21 = new Geometry("bm21", 7.39F, 2.4F, 2.735F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.27F, 1.55F), new Seat("gunner", 0.5F, 1.27F, 1.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			"turret", new float[]{0F, 1.2F, -1.9F}, "pack", new float[]{0F, 0.85F, -1.1F},
			40F, 0F, new Rail[]{new Rail("pack", -0.7425F, 0.07F, 2.85F), new Rail("pack", -0.7425F, 0.565F, 2.85F), new Rail("pack", -0.2475F, 0.07F, 2.85F), new Rail("pack", -0.2475F, 0.565F, 2.85F), new Rail("pack", 0.2475F, 0.07F, 2.85F), new Rail("pack", 0.2475F, 0.565F, 2.85F), new Rail("pack", 0.7425F, 0.07F, 2.85F), new Rail("pack", 0.7425F, 0.565F, 2.85F), new Rail("pack", -0.5775F, 0.3175F, 2.85F), new Rail("pack", -0.0825F, 0.3175F, 2.85F), new Rail("pack", 0.4125F, 0.3175F, 2.85F), new Rail("pack", 0.5775F, 0.3175F, 2.85F)}, null, new String[]{}, 12F,
			1024, 160);

	public static final Geometry ZOOPARK = new Geometry("zoopark", 7.31F, 2.85F, 3.4F, 0F, true,
			new Seat[]{new Seat("driver", -0.65F, 1F, 1.85F), new Seat("gunner", 0.65F, 1F, 1.85F)},
			new Wheel[]{new Wheel("road_0_l", 0.3F, false), new Wheel("road_1_l", 0.3F, false), new Wheel("road_2_l", 0.3F, false), new Wheel("road_3_l", 0.3F, false), new Wheel("road_4_l", 0.3F, false), new Wheel("road_5_l", 0.3F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.3F, false), new Wheel("road_1_r", 0.3F, false), new Wheel("road_2_r", 0.3F, false), new Wheel("road_3_r", 0.3F, false), new Wheel("road_4_r", 0.3F, false), new Wheel("road_5_r", 0.3F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			null, new float[]{0F, 0F, 0F}, "array", new float[]{0F, 2.12F, -2.6F},
			80F, 0F, new Rail[]{}, null, new String[]{}, 11F,
			1024, 240);

	public static final Geometry TPQ36 = new Geometry("tpq36", 9.58F, 2.2F, 2.45F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.45F, 0.72F, 2.1F), new Seat("gunner", 0.45F, 0.72F, 2.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.46F, true), new Wheel("wheel_1_r", 0.46F, true), new Wheel("wheel_2_l", 0.46F, false), new Wheel("wheel_2_r", 0.46F, false), new Wheel("trailer_l", 0.46F, false), new Wheel("trailer_r", 0.46F, false)},
			null, new float[]{0F, 0F, 0F}, "array", new float[]{0F, 1.35F, -4.1F},
			75F, 0F, new Rail[]{}, null, new String[]{}, 12F,
			1024, 96);

	public static final Geometry T80BVM = new Geometry("t80bvm", 10.51F, 3.58F, 5.4F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 0.95F, 2.4F), new Seat("gunner", 0.6F, 2.1F, -0.3F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.5F, -0.2F}, "gun", new float[]{0F, 0.4F, 1.5F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.65F)}, null, new String[]{}, 10F,
			1024, 288);

	public static final Geometry CHALLENGER2 = new Geometry("challenger2", 11.72F, 3.52F, 5.45F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1.05F, 3F), new Seat("gunner", 0.65F, 2.35F, -0.8F)},
			new Wheel[]{new Wheel("road_0_l", 0.38F, false), new Wheel("road_1_l", 0.38F, false), new Wheel("road_2_l", 0.38F, false), new Wheel("road_3_l", 0.38F, false), new Wheel("road_4_l", 0.38F, false), new Wheel("road_5_l", 0.38F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.38F, false), new Wheel("road_1_r", 0.38F, false), new Wheel("road_2_r", 0.38F, false), new Wheel("road_3_r", 0.38F, false), new Wheel("road_4_r", 0.38F, false), new Wheel("road_5_r", 0.38F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.65F, -0.5F}, "gun", new float[]{0F, 0.4F, 1.85F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.65F)}, null, new String[]{}, 11F,
			1024, 352);

	public static final Geometry BMP3 = new Geometry("bmp3", 8.04F, 3.15F, 2.55F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1.15F, 2.4F), new Seat("gunner", 0F, 2.15F, -0.2F)},
			new Wheel[]{new Wheel("road_0_l", 0.32F, false), new Wheel("road_1_l", 0.32F, false), new Wheel("road_2_l", 0.32F, false), new Wheel("road_3_l", 0.32F, false), new Wheel("road_4_l", 0.32F, false), new Wheel("road_5_l", 0.32F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.32F, false), new Wheel("road_1_r", 0.32F, false), new Wheel("road_2_r", 0.32F, false), new Wheel("road_3_r", 0.32F, false), new Wheel("road_4_r", 0.32F, false), new Wheel("road_5_r", 0.32F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.75F, 0.2F}, "gun", new float[]{0F, 0.35F, 1F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 2.95F)}, null, new String[]{}, 10F,
			1024, 256);

	public static final Geometry CV90 = new Geometry("cv90", 7.63F, 3.19F, 2.95F, 0F, true,
			new Seat[]{new Seat("driver", -0.75F, 1.3F, 2.4F), new Seat("gunner", 0F, 2.45F, -0.9F)},
			new Wheel[]{new Wheel("road_0_l", 0.32F, false), new Wheel("road_1_l", 0.32F, false), new Wheel("road_2_l", 0.32F, false), new Wheel("road_3_l", 0.32F, false), new Wheel("road_4_l", 0.32F, false), new Wheel("road_5_l", 0.32F, false), new Wheel("road_6_l", 0.32F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.32F, false), new Wheel("road_1_r", 0.32F, false), new Wheel("road_2_r", 0.32F, false), new Wheel("road_3_r", 0.32F, false), new Wheel("road_4_r", 0.32F, false), new Wheel("road_5_r", 0.32F, false), new Wheel("road_6_r", 0.32F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.95F, -0.4F}, "gun", new float[]{0F, 0.4F, 1.4F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 3.25F)}, null, new String[]{}, 10F,
			1024, 224);

	public static final Geometry STRYKER = new Geometry("stryker", 6.98F, 2.72F, 2.75F, 4.8F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.4F, 2.3F), new Seat("gunner", 0.4F, 2.2F, -0.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, true), new Wheel("wheel_2_r", 0.55F, true), new Wheel("wheel_3_l", 0.55F, false), new Wheel("wheel_3_r", 0.55F, false), new Wheel("wheel_4_l", 0.55F, false), new Wheel("wheel_4_r", 0.55F, false)},
			"turret", new float[]{0F, 2.3F, 0.2F}, "gun", new float[]{0.15F, 0.33F, 0.25F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.5F)}, null, new String[]{}, 10F,
			1024, 144);

	public static final Geometry TIGR = new Geometry("tigr", 5.97F, 2.4F, 2.8F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.5F, 0.94F, 0.8F), new Seat("gunner", 0F, 2.05F, -1.45F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, false), new Wheel("wheel_2_r", 0.55F, false)},
			"turret", new float[]{0F, 2.3F, -1.2F}, "gun", new float[]{0F, 0.35F, 0.38F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.65F)}, null, new String[]{}, 9F,
			1024, 96);

	public static final Geometry HMMWV = new Geometry("hmmwv", 4.98F, 2.2F, 2.6F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.45F, 0.72F, 0.2F), new Seat("gunner", 0F, 0.72F, -0.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.46F, true), new Wheel("wheel_1_r", 0.46F, true), new Wheel("wheel_2_l", 0.46F, false), new Wheel("wheel_2_r", 0.46F, false)},
			"turret", new float[]{0F, 1.98F, -0.3F}, "gun", new float[]{0F, 0.37F, 0.48F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.55F)}, null, new String[]{}, 8F,
			1024, 64);

	public static final Geometry BREM1 = new Geometry("brem1", 8.15F, 3.6F, 2.76F, 0F, true,
			new Seat[]{new Seat("driver", -0.7F, 1.4F, 1.65F), new Seat("gunner", -0.6F, 2.15F, 0.75F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{-0.6F, 2.35F, 1.05F}, "gun", new float[]{0F, 0.35F, 0.45F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.6F)}, null, new String[]{}, 10F,
			1024, 256);

	public static final Geometry M88 = new Geometry("m88", 8.99F, 3.43F, 3.16F, 0F, true,
			new Seat[]{new Seat("driver", -0.8F, 1.75F, 2.5F), new Seat("gunner", 0.9F, 2.55F, 1.8F)},
			new Wheel[]{new Wheel("road_0_l", 0.38F, false), new Wheel("road_1_l", 0.38F, false), new Wheel("road_2_l", 0.38F, false), new Wheel("road_3_l", 0.38F, false), new Wheel("road_4_l", 0.38F, false), new Wheel("road_5_l", 0.38F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.38F, false), new Wheel("road_1_r", 0.38F, false), new Wheel("road_2_r", 0.38F, false), new Wheel("road_3_r", 0.38F, false), new Wheel("road_4_r", 0.38F, false), new Wheel("road_5_r", 0.38F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0.9F, 2.75F, 2.1F}, "gun", new float[]{0F, 0.35F, 0.45F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 1.6F)}, null, new String[]{}, 11F,
			1024, 320);

	public static final Geometry TOS1 = new Geometry("tos1", 6.99F, 3.6F, 2.95F, 0F, true,
			new Seat[]{new Seat("driver", 0F, 1F, 2.3F), new Seat("gunner", 0.9F, 2.05F, 0.2F)},
			new Wheel[]{new Wheel("road_0_l", 0.36F, false), new Wheel("road_1_l", 0.36F, false), new Wheel("road_2_l", 0.36F, false), new Wheel("road_3_l", 0.36F, false), new Wheel("road_4_l", 0.36F, false), new Wheel("road_5_l", 0.36F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.36F, false), new Wheel("road_1_r", 0.36F, false), new Wheel("road_2_r", 0.36F, false), new Wheel("road_3_r", 0.36F, false), new Wheel("road_4_r", 0.36F, false), new Wheel("road_5_r", 0.36F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			"turret", new float[]{0F, 1.55F, -0.6F}, "pack", new float[]{0F, 0.7F, -1.6F},
			35F, 0F, new Rail[]{new Rail("pack", -0.945F, -0.12F, 4.5F), new Rail("pack", -0.945F, 0.5172F, 4.5F), new Rail("pack", -0.135F, -0.12F, 4.5F), new Rail("pack", -0.135F, 0.5172F, 4.5F), new Rail("pack", 0.135F, -0.12F, 4.5F), new Rail("pack", 0.135F, 0.5172F, 4.5F), new Rail("pack", 0.945F, -0.12F, 4.5F), new Rail("pack", 0.945F, 0.5172F, 4.5F)}, null, new String[]{}, 11F,
			1024, 240);

	public static final Geometry AH64 = new Geometry("ah64", 16.65F, 2F, 5.1F, 0F, false,
			new Seat[]{new Seat("driver", 0F, 2.2F, 3.15F), new Seat("gunner", 0F, 1.62F, 4.75F)},
			new Wheel[]{new Wheel("gear_l", 0.32F, false), new Wheel("gear_r", 0.32F, false), new Wheel("gear_tail", 0.18F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "rotor", new String[]{}, 16F,
			1024, 240);

	public static final Geometry A10 = new Geometry("a10", 16.35F, 2.4F, 4.3F, 0F, false,
			new Seat[]{new Seat("driver", 0F, 2.15F, 4.45F)},
			new Wheel[]{new Wheel("gear_nose", 0.33F, false), new Wheel("gear_l", 0.42F, false), new Wheel("gear_r", 0.42F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, null, new String[]{}, 19F,
			1024, 240);

	public static final Geometry BUYAN_M = new Geometry("buyan_m", 74.05F, 11F, 24.7F, 0F, false,
			new Seat[]{new Seat("driver", -1.2F, 9.214F, 9.8F), new Seat("gunner", 1.2F, 9.214F, 9.8F)},
			new Wheel[]{},
			"turret", new float[]{0F, 4.1F, 17F}, "gun", new float[]{0F, 0.8F, 1.4F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 5.95F)}, null, new String[]{}, 46F,
			2048, 2768);

	public static final Geometry VISBY = new Geometry("visby", 72.05F, 10.4F, 14.8F, 0F, false,
			new Seat[]{new Seat("driver", -1F, 8.3F, 11.6F), new Seat("gunner", 1F, 8.3F, 11.6F)},
			new Wheel[]{},
			"turret", new float[]{0F, 3.4F, 24F}, "gun", new float[]{0F, 1.1F, 1.4F},
			0F, 0F, new Rail[]{new Rail("barrel", 0F, 0F, 3.75F)}, null, new String[]{}, 44F,
			2048, 2432);

	public static final Geometry BASTION = new Geometry("bastion", 13.64F, 3.1F, 3.85F, 7.2F, false,
			new Seat[]{new Seat("driver", -0.7F, 1.75F, 5.6F), new Seat("gunner", 0.7F, 1.75F, 5.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.72F, true), new Wheel("wheel_1_r", 0.72F, true), new Wheel("wheel_2_l", 0.72F, true), new Wheel("wheel_2_r", 0.72F, true), new Wheel("wheel_3_l", 0.72F, false), new Wheel("wheel_3_r", 0.72F, false), new Wheel("wheel_4_l", 0.72F, false), new Wheel("wheel_4_r", 0.72F, false)},
			null, new float[]{0F, 0F, 0F}, "container", new float[]{0F, 2.1F, -6.2F},
			90F, 0F, new Rail[]{new Rail("lid_0", -0.65F, 0.85F, 10.6F), new Rail("lid_1", 0.65F, 0.85F, 10.6F)}, null, new String[]{}, 15F,
			1024, 400);

	public static final Geometry NMESIS = new Geometry("nmesis", 6.54F, 2.5F, 2.35F, 3.6F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.04F, 0.8F), new Seat("gunner", 0.5F, 1.04F, 0.8F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, false), new Wheel("wheel_2_r", 0.55F, false)},
			null, new float[]{0F, 0F, 0F}, "pod", new float[]{0F, 1.25F, -2.9F},
			35F, 0F, new Rail[]{new Rail("cap_0", -0.48F, 0.43F, 4.05F), new Rail("cap_1", 0.48F, 0.43F, 4.05F)}, null, new String[]{}, 10F,
			1024, 96);

	public static final Geometry ORLAN = new Geometry("orlan", 7.54F, 2.55F, 3.5F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.55F, 2.6F), new Seat("gunner", 0.55F, 1.55F, 2.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, "catapult", new float[]{0F, 1.4F, -3.6F},
			12F, 6F, new Rail[]{new Rail("uav_0", 0F, 0.35F, 4F), new Rail("box_1", 0F, 0.35F, 4F)}, null, new String[]{}, 12F,
			1024, 160);

	public static final Geometry TB2_GCS = new Geometry("tb2_gcs", 13.84F, 2.55F, 5.2F, 4F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.55F, 3.2F), new Seat("gunner", 0.55F, 1.55F, 3.2F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false), new Wheel("trailer_l", 0.5F, false), new Wheel("trailer_r", 0.5F, false)},
			null, new float[]{0F, 0F, 0F}, "runway", new float[]{0F, 1.2F, 6F},
			4F, 4F, new Rail[]{new Rail("crate_0", 0F, 0.3293F, 1.0255F), new Rail("crate_1", 0F, 0.3293F, 1.0255F)}, null, new String[]{}, 14F,
			1024, 208);

	public static final Geometry LANCET = new Geometry("lancet", 7.54F, 2.55F, 2.9F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.55F, 2.6F), new Seat("gunner", 0.55F, 1.55F, 2.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, "catapult", new float[]{0F, 1.4F, -3.6F},
			15F, 8F, new Rail[]{new Rail("uav_0", 0F, 0.28F, 4.2F), new Rail("box_1", 0F, 0.28F, 4.2F), new Rail("box_2", 0F, 0.28F, 4.2F), new Rail("box_3", 0F, 0.28F, 4.2F)}, null, new String[]{}, 12F,
			1024, 128);

	public static final Geometry SWITCHBLADE = new Geometry("switchblade", 6.34F, 2.5F, 2.35F, 3.6F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.04F, 0.8F), new Seat("gunner", 0.5F, 1.04F, 0.8F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.55F, true), new Wheel("wheel_1_r", 0.55F, true), new Wheel("wheel_2_l", 0.55F, false), new Wheel("wheel_2_r", 0.55F, false)},
			null, new float[]{0F, 0F, 0F}, "pod", new float[]{0F, 1.15F, -2.8F},
			45F, 0F, new Rail[]{new Rail("tube_0", -0.5F, 0.23F, 2.35F), new Rail("tube_1", 0F, 0.23F, 2.35F), new Rail("tube_2", 0.5F, 0.23F, 2.35F), new Rail("tube_3", -0.5F, 0.69F, 2.35F), new Rail("tube_4", 0F, 0.69F, 2.35F), new Rail("tube_5", 0.5F, 0.69F, 2.35F)}, null, new String[]{}, 10F,
			1024, 64);

	public static final Geometry BORISOGLEBSK = new Geometry("borisoglebsk", 6.9F, 2.85F, 4.05F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1F, 1.9F), new Seat("gunner", 0.6F, 1F, 1.9F)},
			new Wheel[]{new Wheel("road_0_l", 0.3F, false), new Wheel("road_1_l", 0.3F, false), new Wheel("road_2_l", 0.3F, false), new Wheel("road_3_l", 0.3F, false), new Wheel("road_4_l", 0.3F, false), new Wheel("road_5_l", 0.3F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.3F, false), new Wheel("road_1_r", 0.3F, false), new Wheel("road_2_r", 0.3F, false), new Wheel("road_3_r", 0.3F, false), new Wheel("road_4_r", 0.3F, false), new Wheel("road_5_r", 0.3F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			null, new float[]{0F, 0F, 0F}, "mast", new float[]{0F, 2.75F, -2.2F},
			90F, 0F, new Rail[]{}, null, new String[]{}, 11F,
			1024, 208);

	public static final Geometry BUKOVEL = new Geometry("bukovel", 5.18F, 2F, 2.4F, 3.1F, false,
			new Seat[]{new Seat("driver", -0.4F, 0.77F, 0.4F), new Seat("gunner", 0.4F, 0.77F, 0.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.42F, true), new Wheel("wheel_1_r", 0.42F, true), new Wheel("wheel_2_l", 0.42F, false), new Wheel("wheel_2_r", 0.42F, false)},
			null, new float[]{0F, 0F, 0F}, "mast", new float[]{0F, 1.7F, -2F},
			90F, 0F, new Rail[]{}, null, new String[]{}, 9F,
			1024, 48);
}
