package com.stasdoto.airdefense.vehicle;

import com.stasdoto.airdefense.vehicle.VehicleGeometry.Geometry;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Rail;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Seat;
import com.stasdoto.airdefense.vehicle.VehicleGeometry.Wheel;

/** GENERATED by tools/models/build.py - do not edit. Geometry of the generated vehicles. */
@SuppressWarnings("unused")
public final class GenGeometry {
	private GenGeometry() {
	}

	public static final Geometry P18 = new Geometry("p18", 7.85F, 2.5F, 7.2F, 4.2F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.45F, 1.55F), new Seat("gunner", 0.5F, 1.45F, 1.55F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, false), new Wheel("wheel_2_r", 0.62F, false), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 144);

	public static final Geometry ST68 = new Geometry("st68", 13.54F, 2.6F, 5.1F, 7F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.6F, 4F), new Seat("gunner", 0.55F, 1.6F, 4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.68F, true), new Wheel("wheel_1_r", 0.68F, true), new Wheel("wheel_2_l", 0.68F, false), new Wheel("wheel_2_r", 0.68F, false), new Wheel("wheel_3_l", 0.68F, false), new Wheel("wheel_3_r", 0.68F, false), new Wheel("trailer_1_l", 0.6F, false), new Wheel("trailer_1_r", 0.6F, false), new Wheel("trailer_2_l", 0.6F, false), new Wheel("trailer_2_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 17F,
			1024, 208);

	public static final Geometry TRML4D = new Geometry("trml4d", 8.79F, 2.55F, 5.2F, 5F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.75F, 3.2F), new Seat("gunner", 0.6F, 1.75F, 3.2F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 160);

	public static final Geometry SENTINEL = new Geometry("sentinel", 9.58F, 2.2F, 3.6F, 3.3F, false,
			new Seat[]{new Seat("driver", -0.45F, 1.05F, 2.1F), new Seat("gunner", 0.45F, 1.05F, 2.1F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.46F, true), new Wheel("wheel_1_r", 0.46F, true), new Wheel("wheel_2_l", 0.46F, false), new Wheel("wheel_2_r", 0.46F, false), new Wheel("trailer_l", 0.46F, false), new Wheel("trailer_r", 0.46F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 12F,
			1024, 112);

	public static final Geometry MPQ65 = new Geometry("mpq65", 13.04F, 2.5F, 3.9F, 7.5F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.85F, 5.6F), new Seat("gunner", 0.55F, 1.85F, 5.6F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.66F, true), new Wheel("wheel_1_r", 0.66F, true), new Wheel("wheel_2_l", 0.66F, true), new Wheel("wheel_2_r", 0.66F, true), new Wheel("rear_1_l", 0.66F, false), new Wheel("rear_1_r", 0.66F, false), new Wheel("rear_2_l", 0.66F, false), new Wheel("rear_2_r", 0.66F, false), new Wheel("trailer_1_l", 0.58F, false), new Wheel("trailer_1_r", 0.58F, false), new Wheel("trailer_2_l", 0.58F, false), new Wheel("trailer_2_r", 0.58F, false)},
			null, new float[]{0F, 0F, 0F}, "array", new float[]{0F, 3.4F, -5.6F},
			72F, 0F, new Rail[]{}, null, new String[]{}, 17F,
			1024, 208);

	public static final Geometry KUPOL = new Geometry("kupol", 9.18F, 3.25F, 5.9F, 0F, true,
			new Seat[]{new Seat("driver", -0.6F, 1.6F, 3.4F), new Seat("gunner", 0.6F, 1.6F, 3.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.33F, false), new Wheel("road_1_l", 0.33F, false), new Wheel("road_2_l", 0.33F, false), new Wheel("road_3_l", 0.33F, false), new Wheel("road_4_l", 0.33F, false), new Wheel("road_5_l", 0.33F, false), new Wheel("sprocket_l", 0.3F, false), new Wheel("idler_l", 0.28F, false), new Wheel("road_0_r", 0.33F, false), new Wheel("road_1_r", 0.33F, false), new Wheel("road_2_r", 0.33F, false), new Wheel("road_3_r", 0.33F, false), new Wheel("road_4_r", 0.33F, false), new Wheel("road_5_r", 0.33F, false), new Wheel("sprocket_r", 0.3F, false), new Wheel("idler_r", 0.28F, false)},
			null, new float[]{0F, 0F, 0F}, null, new float[]{0F, 0F, 0F},
			0F, 0F, new Rail[]{}, "antenna", new String[]{}, 14F,
			1024, 352);
}
