package com.stasdoto.airdefense.vehicle;

/** GENERATED by tools/vehicles/build.py - do not edit. Geometry shared by server logic and rendering. */
public final class VehicleGeometry {
	private VehicleGeometry() {
	}

	/** A seat: role, and the hip point in vehicle space (x right, y up, z forward; metres). */
	public record Seat(String role, float x, float y, float z) {
	}

	public record Wheel(String part, float radius, boolean steer) {
	}

	/** Launch point in the frame of the elevating part (missile centre). */
	public record Rail(String part, float x, float y, float z) {
	}

	public record Geometry(String id, float length, float width, float height, float wheelbase, boolean tracked,
			Seat[] seats, Wheel[] wheels, String turret, float[] turretPivot, String elevator, float[] elevatorPivot,
			float deployElevation, float fixedElevation, Rail[] rails, String spinner, String[] openParts, float camera,
			int textureWidth, int textureHeight) {
	}

	public static final Geometry ISKANDER = new Geometry("iskander", 13.07F, 3.07F, 3.34F, 7.9F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.7F, 5.5F), new Seat("gunner", 0.6F, 1.7F, 5.5F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.75F, true), new Wheel("wheel_1_r", 0.75F, true), new Wheel("wheel_2_l", 0.75F, true), new Wheel("wheel_2_r", 0.75F, true), new Wheel("wheel_3_l", 0.75F, false), new Wheel("wheel_3_r", 0.75F, false), new Wheel("wheel_4_l", 0.75F, false), new Wheel("wheel_4_r", 0.75F, false)},
			null, new float[]{0F, 0F, 0F}, "erector", new float[]{0F, 1.9375F, -5.625F},
			90F, 0F, new Rail[]{new Rail("missile_0", -0.62F, 0.48F, 3.2F), new Rail("missile_1", 0.62F, 0.48F, 3.2F)}, null, new String[]{"roof_l", "roof_r"}, 17F,
			1024, 624);

	public static final Geometry KALIBR = new Geometry("kalibr", 13.07F, 3.07F, 3.6F, 7.9F, false,
			new Seat[]{new Seat("driver", -0.6F, 1.7F, 5.5F), new Seat("gunner", 0.6F, 1.7F, 5.5F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.75F, true), new Wheel("wheel_1_r", 0.75F, true), new Wheel("wheel_2_l", 0.75F, true), new Wheel("wheel_2_r", 0.75F, true), new Wheel("wheel_3_l", 0.75F, false), new Wheel("wheel_3_r", 0.75F, false), new Wheel("wheel_4_l", 0.75F, false), new Wheel("wheel_4_r", 0.75F, false)},
			null, new float[]{0F, 0F, 0F}, "erector", new float[]{0F, 2F, -5.875F},
			55F, 0F, new Rail[]{new Rail("tube_0", -0.45F, 0.5F, 3.8F), new Rail("tube_1", 0.45F, 0.5F, 3.8F), new Rail("tube_2", -0.45F, 1.36F, 3.8F), new Rail("tube_3", 0.45F, 1.36F, 3.8F)}, null, new String[]{}, 17F,
			1024, 560);

	public static final Geometry SHAHED = new Geometry("shahed", 8.6F, 2.5F, 4.4F, 5.3F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.55F, 3.35F), new Seat("gunner", 0.5F, 1.55F, 3.35F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			null, new float[]{0F, 0F, 0F}, "rack", new float[]{0F, 1.375F, -3.875F},
			0F, 15F, new Rail[]{new Rail("drone_0", 0F, 0.5F, 1.8F), new Rail("drone_1", 0F, 1.22F, 1.8F), new Rail("drone_2", 0F, 1.94F, 1.8F), new Rail("drone_3", 0F, 2.66F, 1.8F), new Rail("drone_4", 0F, 3.38F, 1.8F)}, null, new String[]{}, 12F,
			1024, 240);

	public static final Geometry HIMARS = new Geometry("himars", 7F, 2.4F, 3.2F, 4.3F, false,
			new Seat[]{new Seat("driver", -0.5F, 1.45F, 2.7F), new Seat("gunner", 0.5F, 1.45F, 2.7F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.59F, true), new Wheel("wheel_1_r", 0.59F, true), new Wheel("wheel_2_l", 0.59F, false), new Wheel("wheel_2_r", 0.59F, false), new Wheel("wheel_3_l", 0.59F, false), new Wheel("wheel_3_r", 0.59F, false)},
			"turret", new float[]{0F, 1.375F, -1.3125F}, "pod", new float[]{0F, 0.3125F, -2F},
			50F, 0F, new Rail[]{new Rail("pod", -0.7F, 0.92F, 4.3F), new Rail("pod", 0F, 0.92F, 4.3F), new Rail("pod", 0.7F, 0.92F, 4.3F), new Rail("pod", -0.7F, 0.37F, 4.3F), new Rail("pod", 0F, 0.37F, 4.3F), new Rail("pod", 0.7F, 0.37F, 4.3F)}, null, new String[]{}, 11F,
			1024, 160);

	public static final Geometry PATRIOT = new Geometry("patriot", 10.4F, 2.55F, 3.65F, 7.8F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.75F, 4.25F), new Seat("gunner", 0.55F, 1.75F, 4.25F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, true), new Wheel("wheel_2_r", 0.62F, true), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false), new Wheel("wheel_4_l", 0.62F, false), new Wheel("wheel_4_r", 0.62F, false)},
			"turret", new float[]{0F, 1.4375F, -1.625F}, "launcher", new float[]{0F, 0.25F, -2.625F},
			38F, 0F, new Rail[]{new Rail("can_0", -0.5F, 0.58F, 3F), new Rail("can_1", 0.5F, 0.58F, 3F), new Rail("can_2", -0.5F, 1.56F, 3F), new Rail("can_3", 0.5F, 1.56F, 3F)}, null, new String[]{}, 14F,
			1024, 368);

	public static final Geometry IRIS_T = new Geometry("iris_t", 10.2F, 2.55F, 3.5F, 7.6F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.75F, 4.15F), new Seat("gunner", 0.55F, 1.75F, 4.15F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.62F, true), new Wheel("wheel_1_r", 0.62F, true), new Wheel("wheel_2_l", 0.62F, true), new Wheel("wheel_2_r", 0.62F, true), new Wheel("wheel_3_l", 0.62F, false), new Wheel("wheel_3_r", 0.62F, false), new Wheel("wheel_4_l", 0.62F, false), new Wheel("wheel_4_r", 0.62F, false)},
			null, new float[]{0F, 0F, 0F}, "launcher", new float[]{0F, 1.5625F, -4.8125F},
			90F, 0F, new Rail[]{new Rail("can_0", -0.66F, 0.3F, 2F), new Rail("can_1", -0.22F, 0.3F, 2F), new Rail("can_2", 0.22F, 0.3F, 2F), new Rail("can_3", 0.66F, 0.3F, 2F), new Rail("can_4", -0.66F, 0.74F, 2F), new Rail("can_5", -0.22F, 0.74F, 2F), new Rail("can_6", 0.22F, 0.74F, 2F), new Rail("can_7", 0.66F, 0.74F, 2F)}, null, new String[]{}, 14F,
			1024, 320);

	public static final Geometry NASAMS = new Geometry("nasams", 8.6F, 2.55F, 3.4F, 5.3F, false,
			new Seat[]{new Seat("driver", -0.55F, 1.7F, 3.4F), new Seat("gunner", 0.55F, 1.7F, 3.4F)},
			new Wheel[]{new Wheel("wheel_1_l", 0.6F, true), new Wheel("wheel_1_r", 0.6F, true), new Wheel("wheel_2_l", 0.6F, false), new Wheel("wheel_2_r", 0.6F, false), new Wheel("wheel_3_l", 0.6F, false), new Wheel("wheel_3_r", 0.6F, false)},
			"turret", new float[]{0F, 1.375F, -1F}, "launcher", new float[]{0F, 0.3125F, -2.625F},
			30F, 0F, new Rail[]{new Rail("can_0", -0.62F, 0.36F, 2.1F), new Rail("can_1", 0F, 0.36F, 2.1F), new Rail("can_2", 0.62F, 0.36F, 2.1F), new Rail("can_3", -0.62F, 0.98F, 2.1F), new Rail("can_4", 0F, 0.98F, 2.1F), new Rail("can_5", 0.62F, 0.98F, 2.1F)}, null, new String[]{}, 12F,
			1024, 256);

	public static final Geometry GEPARD = new Geometry("gepard", 7.7F, 3.7F, 4F, 0F, true,
			new Seat[]{new Seat("driver", -0.75F, 1.25F, 2.3F), new Seat("gunner", 0F, 2.35F, -0.4F)},
			new Wheel[]{new Wheel("road_0_l", 0.33F, false), new Wheel("road_1_l", 0.33F, false), new Wheel("road_2_l", 0.33F, false), new Wheel("road_3_l", 0.33F, false), new Wheel("road_4_l", 0.33F, false), new Wheel("road_5_l", 0.33F, false), new Wheel("road_6_l", 0.33F, false), new Wheel("sprocket_l", 0.36F, false), new Wheel("idler_l", 0.33F, false), new Wheel("road_0_r", 0.33F, false), new Wheel("road_1_r", 0.33F, false), new Wheel("road_2_r", 0.33F, false), new Wheel("road_3_r", 0.33F, false), new Wheel("road_4_r", 0.33F, false), new Wheel("road_5_r", 0.33F, false), new Wheel("road_6_r", 0.33F, false), new Wheel("sprocket_r", 0.36F, false), new Wheel("idler_r", 0.33F, false)},
			"turret", new float[]{0F, 1.625F, -0.375F}, "guns", new float[]{0F, 0.6875F, 0.375F},
			0F, 0F, new Rail[]{new Rail("barrel_l", -1.52F, 0F, 4.1F), new Rail("barrel_r", 1.52F, 0F, 4.1F)}, "radar", new String[]{}, 11F,
			1024, 240);

}
