package com.stasdoto.airdefense.weapon;

/**
 * GENERATED by tools/guns/build.py - do not edit. Where the muzzle of each gun model is: metres ahead of the grip,
 * and in first person (camera space: right, up, ahead) at the hip and aimed.
 */
public final class GunModels {
	private GunModels() {
	}

	public static double muzzle(String id) {
		return switch (id) {
			case "ak74" -> 0.611;
			case "akm" -> 0.547;
			case "ak12" -> 0.595;
			case "aks74u" -> 0.384;
			case "rpk74" -> 0.762;
			case "saiga12" -> 0.630;
			case "bizon" -> 0.415;
			case "m4a1" -> 0.474;
			case "m16a4" -> 0.609;
			case "hk416" -> 0.440;
			case "scarh" -> 0.510;
			case "m110" -> 0.610;
			case "m249" -> 0.620;
			case "m240b" -> 0.840;
			case "pkm" -> 0.670;
			case "pkp" -> 0.660;
			case "svd" -> 0.840;
			case "sv98" -> 0.710;
			case "vss" -> 0.450;
			case "asval" -> 0.450;
			case "m82" -> 0.960;
			case "awm" -> 0.730;
			case "fort221" -> 0.389;
			case "mp5" -> 0.250;
			case "m870" -> 0.660;
			case "pm" -> 0.110;
			case "fort12" -> 0.124;
			case "glock17" -> 0.134;
			case "rpg7" -> 0.685;
			case "rpg22" -> 0.420;
			case "at4" -> 0.500;
			case "cg84" -> 0.450;
			case "nlaw" -> 0.500;
			case "javelin" -> 0.620;
			case "m32" -> 0.510;
			default -> 0.6;
		};
	}

	/** {right, up, ahead} of the camera, blocks. */
	public static double[] view(String id, boolean aim) {
		return switch (id) {
			case "ak74" -> aim ? new double[]{0.000, -0.053, 0.911} : new double[]{0.261, -0.127, 0.926};
			case "akm" -> aim ? new double[]{0.000, -0.053, 0.847} : new double[]{0.255, -0.131, 0.862};
			case "ak12" -> aim ? new double[]{0.000, -0.087, 0.895} : new double[]{0.259, -0.128, 0.910};
			case "aks74u" -> aim ? new double[]{0.000, -0.053, 0.684} : new double[]{0.241, -0.139, 0.700};
			case "rpk74" -> aim ? new double[]{0.000, -0.053, 1.062} : new double[]{0.274, -0.119, 1.076};
			case "saiga12" -> aim ? new double[]{0.000, -0.053, 0.930} : new double[]{0.262, -0.126, 0.945};
			case "bizon" -> aim ? new double[]{0.000, -0.052, 0.715} : new double[]{0.244, -0.137, 0.731};
			case "m4a1" -> aim ? new double[]{0.000, -0.071, 0.774} : new double[]{0.248, -0.120, 0.789};
			case "m16a4" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.260, -0.113, 0.923};
			case "hk416" -> aim ? new double[]{0.000, -0.073, 0.740} : new double[]{0.245, -0.122, 0.755};
			case "scarh" -> aim ? new double[]{0.000, -0.074, 0.810} : new double[]{0.251, -0.119, 0.825};
			case "m110" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.259, -0.109, 0.924};
			case "m249" -> aim ? new double[]{0.000, -0.069, 0.920} : new double[]{0.261, -0.119, 0.935};
			case "m240b" -> aim ? new double[]{0.000, -0.081, 1.140} : new double[]{0.280, -0.099, 1.153};
			case "pkm" -> aim ? new double[]{0.000, -0.067, 0.970} : new double[]{0.265, -0.116, 0.985};
			case "pkp" -> aim ? new double[]{0.000, -0.077, 0.960} : new double[]{0.264, -0.117, 0.975};
			case "svd" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.281, -0.115, 1.154};
			case "sv98" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.269, -0.120, 1.025};
			case "vss" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.247, -0.136, 0.766};
			case "asval" -> aim ? new double[]{0.000, -0.055, 0.750} : new double[]{0.247, -0.136, 0.766};
			case "m82" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.291, -0.105, 1.273};
			case "awm" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.271, -0.117, 1.044};
			case "fort221" -> aim ? new double[]{0.000, -0.077, 0.689} : new double[]{0.241, -0.129, 0.705};
			case "mp5" -> aim ? new double[]{0.000, -0.053, 0.550} : new double[]{0.229, -0.144, 0.567};
			case "m870" -> aim ? new double[]{0.000, -0.047, 0.960} : new double[]{0.265, -0.119, 0.975};
			case "pm" -> aim ? new double[]{0.000, -0.032, 0.430} : new double[]{0.203, -0.188, 0.455};
			case "fort12" -> aim ? new double[]{0.000, -0.033, 0.444} : new double[]{0.204, -0.187, 0.469};
			case "glock17" -> aim ? new double[]{0.000, -0.033, 0.454} : new double[]{0.205, -0.186, 0.479};
			case "rpg7" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.266, -0.107, 0.999};
			case "rpg22" -> aim ? new double[]{0.030, -0.063, 0.720} : new double[]{0.244, -0.135, 0.736};
			case "at4" -> aim ? new double[]{0.040, -0.083, 0.800} : new double[]{0.249, -0.109, 0.815};
			case "cg84" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.245, -0.116, 0.765};
			case "nlaw" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.249, -0.099, 0.814};
			case "javelin" -> aim ? new double[]{0.000, -0.060, 0.900} : new double[]{0.257, -0.063, 0.932};
			case "m32" -> aim ? new double[]{0.000, -0.081, 0.810} : new double[]{0.251, -0.123, 0.825};
			default -> aim ? new double[]{0, -0.07, 1.1} : new double[]{0.3, -0.25, 1.0};
		};
	}
}
