#!/usr/bin/env python3
"""
Builds every gun: python3 tools/guns/build.py              (models, textures, icons, item definitions)
                  python3 tools/guns/build.py preview DIR  (big side views of the textured guns, to look at)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gunkit  # noqa: E402
import ak  # noqa: E402

MODULES = [ak]
for name in ('ar', 'others', 'launchers'):
    try:
        MODULES.append(__import__(name))
    except ModuleNotFoundError:
        pass

JAVA = os.path.abspath(os.path.join(HERE, '..', '..', 'src', 'main', 'java', 'com', 'stasdoto', 'airdefense', 'weapon', 'GunModels.java'))


def guns(only=None):
    out = []
    for m in MODULES:
        for make in m.ALL:
            g = make()
            if only and g.id not in only:
                continue
            out.append(g)
    return out


def java(stats):
    """GunModels.java: where each model's muzzle is, for the flash and the tracer's start in first person."""
    lines = ['package com.stasdoto.airdefense.weapon;', '',
             '/**',
             ' * GENERATED by tools/guns/build.py - do not edit. Where the muzzle of each gun model is: metres ahead of the grip,',
             ' * and in first person (camera space: right, up, ahead) at the hip and aimed.',
             ' */',
             'public final class GunModels {', '\tprivate GunModels() {', '\t}', '',
             '\tpublic static double muzzle(String id) {', '\t\treturn switch (id) {']
    for s in stats:
        lines.append('\t\t\tcase "%s" -> %.3f;' % (s['id'], s['muzzle']))
    lines += ['\t\t\tdefault -> 0.6;', '\t\t};', '\t}', '',
              '\t/** {right, up, ahead} of the camera, blocks. */',
              '\tpublic static double[] view(String id, boolean aim) {', '\t\treturn switch (id) {']
    for s in stats:
        h, a = s['hip'], s['aim']
        lines.append('\t\t\tcase "%s" -> aim ? new double[]{%.3f, %.3f, %.3f} : new double[]{%.3f, %.3f, %.3f};'
                     % (s['id'], a[0], a[1], -a[2], h[0], h[1], -h[2]))
    lines += ['\t\t\tdefault -> aim ? new double[]{0, -0.07, 1.1} : new double[]{0.3, -0.25, 1.0};', '\t\t};', '\t}', '}', '']
    with open(JAVA, 'w') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    if len(sys.argv) > 2 and sys.argv[1] == 'preview':
        out = sys.argv[2]
        os.makedirs(out, exist_ok=True)
        for g in guns(sys.argv[3:]):
            gunkit.preview(g, os.path.join(out, g.id + '.png'))
            print(g.id, len(g.boxes))
        sys.exit(0)
    only = sys.argv[1:]
    stats = [gunkit.export(g) for g in guns(only)]
    for s in stats:
        print('%-10s boxes %4d atlas %4dx%-4d scale %.3f k %.3f muzzle %.2f' % (s['id'], s['boxes'], s['atlas'][0], s['atlas'][1], s['scale'], s['k'], s['muzzle']))
    if not only:
        java(stats)
        print('total boxes', sum(s['boxes'] for s in stats), 'texels', sum(s['atlas'][0] * s['atlas'][1] for s in stats))
