package com.stasdoto.airdefense.client.gear;

import java.util.EnumSet;
import java.util.Map;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.core.Direction;

/** GENERATED by tools/models/gear.py - do not edit. The gear drawn on people, at four times the size. */
@SuppressWarnings("unused")
public final class GenGear {
	/** Model units per pixel of the person (drawn at 1 / SCALE). */
	public static final int SCALE = 4;

	private GenGear() {
	}

	public static LayerDefinition layer(String id) {
		return switch (id) {
			case "helmet_6b47" -> helmet_6b47();
			case "helmet_fast" -> helmet_fast();
			case "helmet_fast_nvg" -> helmet_fast_nvg();
			case "vest_pc" -> vest_pc();
			case "vest_6b45" -> vest_6b45();
			case "pouch_mag_mc" -> pouch_mag_mc();
			case "pouch_grenade_mc" -> pouch_grenade_mc();
			case "pouch_medkit_mc" -> pouch_medkit_mc();
			case "pouch_radio_mc" -> pouch_radio_mc();
			case "pouch_mag_emr" -> pouch_mag_emr();
			case "pouch_grenade_emr" -> pouch_grenade_emr();
			case "pouch_medkit_emr" -> pouch_medkit_emr();
			case "pouch_radio_emr" -> pouch_radio_emr();
			default -> throw new IllegalArgumentException(id);
		};
	}

	public static Map<String, String> paths(String id) {
		return switch (id) {
			case "helmet_6b47" -> helmet_6b47Paths();
			case "helmet_fast" -> helmet_fastPaths();
			case "helmet_fast_nvg" -> helmet_fast_nvgPaths();
			case "vest_pc" -> vest_pcPaths();
			case "vest_6b45" -> vest_6b45Paths();
			case "pouch_mag_mc" -> pouch_mag_mcPaths();
			case "pouch_grenade_mc" -> pouch_grenade_mcPaths();
			case "pouch_medkit_mc" -> pouch_medkit_mcPaths();
			case "pouch_radio_mc" -> pouch_radio_mcPaths();
			case "pouch_mag_emr" -> pouch_mag_emrPaths();
			case "pouch_grenade_emr" -> pouch_grenade_emrPaths();
			case "pouch_medkit_emr" -> pouch_medkit_emrPaths();
			case "pouch_radio_emr" -> pouch_radio_emrPaths();
			default -> throw new IllegalArgumentException(id);
		};
	}

	public static LayerDefinition helmet_6b47() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("helmet", CubeListBuilder.create()
				.texOffs(0, 85).addBox(-21F, -25.6F, -13.928F, 42F, 4F, 26F)
				.texOffs(0, 0).addBox(-13.728F, -25.6F, -21.2F, 27F, 4F, 40F)
				.texOffs(282, 85).addBox(-20.9249F, -28F, -13.8818F, 42F, 2F, 26F)
				.texOffs(134, 0).addBox(-13.6789F, -28F, -21.1277F, 27F, 2F, 40F)
				.texOffs(136, 115).addBox(-20.3892F, -30F, -13.552F, 41F, 2F, 25F)
				.texOffs(0, 44).addBox(-13.3287F, -30F, -20.6124F, 27F, 2F, 39F)
				.texOffs(356, 115).addBox(-19.4824F, -31.8F, -12.9938F, 39F, 2F, 24F)
				.texOffs(132, 44).addBox(-12.7359F, -31.8F, -19.7402F, 25F, 2F, 37F)
				.texOffs(0, 143).addBox(-18.2711F, -33.4F, -12.248F, 37F, 2F, 22F)
				.texOffs(256, 44).addBox(-11.9441F, -33.4F, -18.5751F, 24F, 2F, 35F)
				.texOffs(192, 143).addBox(-16.8221F, -34.8F, -11.356F, 34F, 1F, 21F)
				.texOffs(374, 44).addBox(-10.9969F, -34.8F, -17.1813F, 22F, 1F, 32F)
				.texOffs(302, 143).addBox(-15.1972F, -36F, -10.3557F, 30F, 1F, 19F)
				.texOffs(136, 85).addBox(-9.9346F, -36F, -15.6182F, 20F, 1F, 29F)
				.texOffs(0, 167).addBox(-13.4594F, -37F, -9.2858F, 27F, 1F, 17F)
				.texOffs(268, 115).addBox(-8.7986F, -37F, -13.9466F, 18F, 1F, 26F)
				.texOffs(298, 167).addBox(-11.6822F, -37.8F, -8.1918F, 23F, 1F, 14F)
				.texOffs(118, 143).addBox(-7.6368F, -37.8F, -12.2371F, 15F, 1F, 22F)
				.texOffs(372, 167).addBox(-9.8529F, -38.48F, -7.0657F, 20F, 1F, 12F)
				.texOffs(400, 143).addBox(-6.441F, -38.48F, -10.4776F, 13F, 1F, 19F)
				.texOffs(0, 185).addBox(-7.8887F, -39.04F, -5.8564F, 16F, 1F, 10F)
				.texOffs(218, 167).addBox(-5.157F, -39.04F, -8.5882F, 10F, 1F, 15F)
				.texOffs(82, 185).addBox(-5.6309F, -39.52F, -4.4665F, 11F, 1F, 7F)
				.texOffs(436, 167).addBox(-3.681F, -39.52F, -6.4164F, 7F, 1F, 11F)
				.texOffs(234, 85).addBox(-21F, -21.2F, -13.8F, 5F, 11F, 19F)
				.texOffs(472, 167).addBox(-21F, -21.2F, 5.4F, 5F, 6F, 6F)
				.texOffs(234, 85).addBox(15.6F, -21.2F, -13.8F, 5F, 11F, 19F)
				.texOffs(472, 167).addBox(15.6F, -21.2F, 5.4F, 5F, 6F, 6F)
				.texOffs(94, 167).addBox(-13.6F, -21.2F, -21.2F, 27F, 12F, 5F)
				.texOffs(0, 115).addBox(-20.92F, -29.4F, -13.92F, 42F, 2F, 26F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				.texOffs(268, 0).addBox(-13.72F, -29.4F, -21.12F, 27F, 2F, 40F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				.texOffs(206, 185).addBox(-4F, -30F, 18.8F, 8F, 5F, 2F)
				.texOffs(364, 185).addBox(-2.4F, -29F, 20.4F, 5F, 3F, 1F)
				.texOffs(226, 185).addBox(-2F, -26.4F, -22.4F, 4F, 5F, 2F)
				.texOffs(88, 167).addBox(-19.2F, -17.6F, 1.4F, 1F, 16F, 2F)
				.texOffs(88, 167).addBox(18.2F, -17.6F, 1.4F, 1F, 16F, 2F)
				.texOffs(238, 185).addBox(-5.2F, -1.4F, 15.6F, 10F, 3F, 3F)
				.texOffs(158, 167).addBox(-19.2F, -0.6F, 1.4F, 14F, 1F, 16F)
				.texOffs(158, 167).addBox(5.2F, -0.6F, 1.4F, 14F, 1F, 16F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("helmet_c1", CubeListBuilder.create()
				.texOffs(52, 185).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, -15.6753F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("helmet_c2", CubeListBuilder.create()
				.texOffs(52, 185).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, 13.6753F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("helmet_c3", CubeListBuilder.create()
				.texOffs(52, 185).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, -15.6753F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("helmet_c4", CubeListBuilder.create()
				.texOffs(52, 185).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, 13.6753F, 0F, 0.7854F, 0F));
		PartDefinition p5 = p0.addOrReplaceChild("helmet_c5", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, -15.6225F, 0F, 0.7854F, 0F));
		PartDefinition p6 = p0.addOrReplaceChild("helmet_c6", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, 13.6225F, 0F, -0.7854F, 0F));
		PartDefinition p7 = p0.addOrReplaceChild("helmet_c7", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, -15.6225F, 0F, -0.7854F, 0F));
		PartDefinition p8 = p0.addOrReplaceChild("helmet_c8", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, 13.6225F, 0F, 0.7854F, 0F));
		PartDefinition p9 = p0.addOrReplaceChild("helmet_c9", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, -15.2464F, 0F, 0.7854F, 0F));
		PartDefinition p10 = p0.addOrReplaceChild("helmet_c10", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, 13.2464F, 0F, -0.7854F, 0F));
		PartDefinition p11 = p0.addOrReplaceChild("helmet_c11", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, -15.2464F, 0F, -0.7854F, 0F));
		PartDefinition p12 = p0.addOrReplaceChild("helmet_c12", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, 13.2464F, 0F, 0.7854F, 0F));
		PartDefinition p13 = p0.addOrReplaceChild("helmet_c13", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, -14.6097F, 0F, 0.7854F, 0F));
		PartDefinition p14 = p0.addOrReplaceChild("helmet_c14", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, 12.6097F, 0F, -0.7854F, 0F));
		PartDefinition p15 = p0.addOrReplaceChild("helmet_c15", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, -14.6097F, 0F, -0.7854F, 0F));
		PartDefinition p16 = p0.addOrReplaceChild("helmet_c16", CubeListBuilder.create()
				.texOffs(118, 185).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, 12.6097F, 0F, 0.7854F, 0F));
		PartDefinition p17 = p0.addOrReplaceChild("helmet_c17", CubeListBuilder.create()
				.texOffs(178, 185).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, -13.7591F, 0F, 0.7854F, 0F));
		PartDefinition p18 = p0.addOrReplaceChild("helmet_c18", CubeListBuilder.create()
				.texOffs(178, 185).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, 11.7591F, 0F, -0.7854F, 0F));
		PartDefinition p19 = p0.addOrReplaceChild("helmet_c19", CubeListBuilder.create()
				.texOffs(178, 185).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, -13.7591F, 0F, -0.7854F, 0F));
		PartDefinition p20 = p0.addOrReplaceChild("helmet_c20", CubeListBuilder.create()
				.texOffs(178, 185).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, 11.7591F, 0F, 0.7854F, 0F));
		PartDefinition p21 = p0.addOrReplaceChild("helmet_c21", CubeListBuilder.create()
				.texOffs(264, 185).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, -12.7416F, 0F, 0.7854F, 0F));
		PartDefinition p22 = p0.addOrReplaceChild("helmet_c22", CubeListBuilder.create()
				.texOffs(264, 185).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, 10.7416F, 0F, -0.7854F, 0F));
		PartDefinition p23 = p0.addOrReplaceChild("helmet_c23", CubeListBuilder.create()
				.texOffs(264, 185).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, -12.7416F, 0F, -0.7854F, 0F));
		PartDefinition p24 = p0.addOrReplaceChild("helmet_c24", CubeListBuilder.create()
				.texOffs(264, 185).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, 10.7416F, 0F, 0.7854F, 0F));
		PartDefinition p25 = p0.addOrReplaceChild("helmet_c25", CubeListBuilder.create()
				.texOffs(288, 185).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, -11.6006F, 0F, 0.7854F, 0F));
		PartDefinition p26 = p0.addOrReplaceChild("helmet_c26", CubeListBuilder.create()
				.texOffs(288, 185).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, 9.6006F, 0F, -0.7854F, 0F));
		PartDefinition p27 = p0.addOrReplaceChild("helmet_c27", CubeListBuilder.create()
				.texOffs(288, 185).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, -11.6006F, 0F, -0.7854F, 0F));
		PartDefinition p28 = p0.addOrReplaceChild("helmet_c28", CubeListBuilder.create()
				.texOffs(288, 185).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, 9.6006F, 0F, 0.7854F, 0F));
		PartDefinition p29 = p0.addOrReplaceChild("helmet_c29", CubeListBuilder.create()
				.texOffs(310, 185).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, -10.3803F, 0F, 0.7854F, 0F));
		PartDefinition p30 = p0.addOrReplaceChild("helmet_c30", CubeListBuilder.create()
				.texOffs(310, 185).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, 8.3803F, 0F, -0.7854F, 0F));
		PartDefinition p31 = p0.addOrReplaceChild("helmet_c31", CubeListBuilder.create()
				.texOffs(310, 185).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, -10.3803F, 0F, -0.7854F, 0F));
		PartDefinition p32 = p0.addOrReplaceChild("helmet_c32", CubeListBuilder.create()
				.texOffs(310, 185).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, 8.3803F, 0F, 0.7854F, 0F));
		PartDefinition p33 = p0.addOrReplaceChild("helmet_c33", CubeListBuilder.create()
				.texOffs(330, 185).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, -9.1324F, 0F, 0.7854F, 0F));
		PartDefinition p34 = p0.addOrReplaceChild("helmet_c34", CubeListBuilder.create()
				.texOffs(330, 185).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, 7.1324F, 0F, -0.7854F, 0F));
		PartDefinition p35 = p0.addOrReplaceChild("helmet_c35", CubeListBuilder.create()
				.texOffs(330, 185).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, -9.1324F, 0F, -0.7854F, 0F));
		PartDefinition p36 = p0.addOrReplaceChild("helmet_c36", CubeListBuilder.create()
				.texOffs(330, 185).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, 7.1324F, 0F, 0.7854F, 0F));
		PartDefinition p37 = p0.addOrReplaceChild("helmet_c37", CubeListBuilder.create()
				.texOffs(348, 185).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, -7.8479F, 0F, 0.7854F, 0F));
		PartDefinition p38 = p0.addOrReplaceChild("helmet_c38", CubeListBuilder.create()
				.texOffs(348, 185).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, 5.8479F, 0F, -0.7854F, 0F));
		PartDefinition p39 = p0.addOrReplaceChild("helmet_c39", CubeListBuilder.create()
				.texOffs(348, 185).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, -7.8479F, 0F, -0.7854F, 0F));
		PartDefinition p40 = p0.addOrReplaceChild("helmet_c40", CubeListBuilder.create()
				.texOffs(348, 185).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, 5.8479F, 0F, 0.7854F, 0F));
		PartDefinition p41 = p0.addOrReplaceChild("helmet_c41", CubeListBuilder.create()
				.texOffs(376, 185).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, -6.4687F, 0F, 0.7854F, 0F));
		PartDefinition p42 = p0.addOrReplaceChild("helmet_c42", CubeListBuilder.create()
				.texOffs(376, 185).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, 4.4687F, 0F, -0.7854F, 0F));
		PartDefinition p43 = p0.addOrReplaceChild("helmet_c43", CubeListBuilder.create()
				.texOffs(376, 185).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, -6.4687F, 0F, -0.7854F, 0F));
		PartDefinition p44 = p0.addOrReplaceChild("helmet_c44", CubeListBuilder.create()
				.texOffs(376, 185).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, 4.4687F, 0F, 0.7854F, 0F));
		PartDefinition p45 = p0.addOrReplaceChild("helmet_c45", CubeListBuilder.create()
				.texOffs(388, 185).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, -4.8833F, 0F, 0.7854F, 0F));
		PartDefinition p46 = p0.addOrReplaceChild("helmet_c46", CubeListBuilder.create()
				.texOffs(388, 185).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, 2.8833F, 0F, -0.7854F, 0F));
		PartDefinition p47 = p0.addOrReplaceChild("helmet_c47", CubeListBuilder.create()
				.texOffs(388, 185).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, -4.8833F, 0F, -0.7854F, 0F));
		PartDefinition p48 = p0.addOrReplaceChild("helmet_c48", CubeListBuilder.create()
				.texOffs(388, 185).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, 2.8833F, 0F, 0.7854F, 0F));
		PartDefinition p49 = p0.addOrReplaceChild("helmet_c49", CubeListBuilder.create()
				.texOffs(268, 167).addBox(-5.0912F, -21.2F, -2.6456F, 10F, 11F, 5F)
				, PartPose.offsetAndRotation(-15.5293F, 0F, -15.7293F, 0F, 0.7854F, 0F));
		PartDefinition p50 = p0.addOrReplaceChild("helmet_c50", CubeListBuilder.create()
				.texOffs(268, 167).addBox(-5.0912F, -21.2F, -2.6456F, 10F, 11F, 5F)
				, PartPose.offsetAndRotation(15.5293F, 0F, -15.7293F, 0F, -0.7854F, 0F));
		PartDefinition p51 = p0.addOrReplaceChild("helmet_c51", CubeListBuilder.create()
				.texOffs(148, 185).addBox(-5.0912F, -29.4F, -2.6456F, 10F, 2F, 5F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				, PartPose.offsetAndRotation(-15.4493F, 0F, -15.6493F, 0F, 0.7854F, 0F));
		PartDefinition p52 = p0.addOrReplaceChild("helmet_c52", CubeListBuilder.create()
				.texOffs(148, 185).addBox(-5.0912F, -29.4F, -2.6456F, 10F, 2F, 5F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				, PartPose.offsetAndRotation(-15.4493F, 0F, 13.6493F, 0F, -0.7854F, 0F));
		PartDefinition p53 = p0.addOrReplaceChild("helmet_c53", CubeListBuilder.create()
				.texOffs(148, 185).addBox(-5.0912F, -29.4F, -2.6456F, 10F, 2F, 5F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				, PartPose.offsetAndRotation(15.4493F, 0F, -15.6493F, 0F, -0.7854F, 0F));
		PartDefinition p54 = p0.addOrReplaceChild("helmet_c54", CubeListBuilder.create()
				.texOffs(148, 185).addBox(-5.0912F, -29.4F, -2.6456F, 10F, 2F, 5F, EnumSet.of(Direction.SOUTH, Direction.NORTH, Direction.WEST, Direction.EAST))
				, PartPose.offsetAndRotation(15.4493F, 0F, 13.6493F, 0F, 0.7854F, 0F));
		return LayerDefinition.create(mesh, 512, 208);
	}

	public static Map<String, String> helmet_6b47Paths() {
		return Map.ofEntries(
				Map.entry("helmet", "helmet"),
				Map.entry("helmet_c1", "helmet/helmet_c1"),
				Map.entry("helmet_c2", "helmet/helmet_c2"),
				Map.entry("helmet_c3", "helmet/helmet_c3"),
				Map.entry("helmet_c4", "helmet/helmet_c4"),
				Map.entry("helmet_c5", "helmet/helmet_c5"),
				Map.entry("helmet_c6", "helmet/helmet_c6"),
				Map.entry("helmet_c7", "helmet/helmet_c7"),
				Map.entry("helmet_c8", "helmet/helmet_c8"),
				Map.entry("helmet_c9", "helmet/helmet_c9"),
				Map.entry("helmet_c10", "helmet/helmet_c10"),
				Map.entry("helmet_c11", "helmet/helmet_c11"),
				Map.entry("helmet_c12", "helmet/helmet_c12"),
				Map.entry("helmet_c13", "helmet/helmet_c13"),
				Map.entry("helmet_c14", "helmet/helmet_c14"),
				Map.entry("helmet_c15", "helmet/helmet_c15"),
				Map.entry("helmet_c16", "helmet/helmet_c16"),
				Map.entry("helmet_c17", "helmet/helmet_c17"),
				Map.entry("helmet_c18", "helmet/helmet_c18"),
				Map.entry("helmet_c19", "helmet/helmet_c19"),
				Map.entry("helmet_c20", "helmet/helmet_c20"),
				Map.entry("helmet_c21", "helmet/helmet_c21"),
				Map.entry("helmet_c22", "helmet/helmet_c22"),
				Map.entry("helmet_c23", "helmet/helmet_c23"),
				Map.entry("helmet_c24", "helmet/helmet_c24"),
				Map.entry("helmet_c25", "helmet/helmet_c25"),
				Map.entry("helmet_c26", "helmet/helmet_c26"),
				Map.entry("helmet_c27", "helmet/helmet_c27"),
				Map.entry("helmet_c28", "helmet/helmet_c28"),
				Map.entry("helmet_c29", "helmet/helmet_c29"),
				Map.entry("helmet_c30", "helmet/helmet_c30"),
				Map.entry("helmet_c31", "helmet/helmet_c31"),
				Map.entry("helmet_c32", "helmet/helmet_c32"),
				Map.entry("helmet_c33", "helmet/helmet_c33"),
				Map.entry("helmet_c34", "helmet/helmet_c34"),
				Map.entry("helmet_c35", "helmet/helmet_c35"),
				Map.entry("helmet_c36", "helmet/helmet_c36"),
				Map.entry("helmet_c37", "helmet/helmet_c37"),
				Map.entry("helmet_c38", "helmet/helmet_c38"),
				Map.entry("helmet_c39", "helmet/helmet_c39"),
				Map.entry("helmet_c40", "helmet/helmet_c40"),
				Map.entry("helmet_c41", "helmet/helmet_c41"),
				Map.entry("helmet_c42", "helmet/helmet_c42"),
				Map.entry("helmet_c43", "helmet/helmet_c43"),
				Map.entry("helmet_c44", "helmet/helmet_c44"),
				Map.entry("helmet_c45", "helmet/helmet_c45"),
				Map.entry("helmet_c46", "helmet/helmet_c46"),
				Map.entry("helmet_c47", "helmet/helmet_c47"),
				Map.entry("helmet_c48", "helmet/helmet_c48"),
				Map.entry("helmet_c49", "helmet/helmet_c49"),
				Map.entry("helmet_c50", "helmet/helmet_c50"),
				Map.entry("helmet_c51", "helmet/helmet_c51"),
				Map.entry("helmet_c52", "helmet/helmet_c52"),
				Map.entry("helmet_c53", "helmet/helmet_c53"),
				Map.entry("helmet_c54", "helmet/helmet_c54")
		);
	}

	public static LayerDefinition helmet_fast() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("helmet", CubeListBuilder.create()
				.texOffs(350, 44).addBox(-21F, -25.6F, -13.728F, 42F, 4F, 26F)
				.texOffs(0, 0).addBox(-13.728F, -25.6F, -21F, 27F, 4F, 40F)
				.texOffs(98, 83).addBox(-20.9249F, -28F, -13.6818F, 42F, 2F, 26F)
				.texOffs(134, 0).addBox(-13.6789F, -28F, -20.9277F, 27F, 2F, 40F)
				.texOffs(234, 83).addBox(-20.3892F, -30F, -13.352F, 41F, 2F, 25F)
				.texOffs(268, 0).addBox(-13.3287F, -30F, -20.4124F, 27F, 2F, 39F)
				.texOffs(0, 113).addBox(-19.4824F, -31.8F, -12.7938F, 39F, 2F, 24F)
				.texOffs(0, 44).addBox(-12.7359F, -31.8F, -19.5402F, 25F, 2F, 37F)
				.texOffs(174, 113).addBox(-18.2711F, -33.4F, -12.048F, 37F, 2F, 22F)
				.texOffs(124, 44).addBox(-11.9441F, -33.4F, -18.3751F, 24F, 2F, 35F)
				.texOffs(372, 113).addBox(-16.8221F, -34.8F, -11.156F, 34F, 1F, 21F)
				.texOffs(242, 44).addBox(-10.9969F, -34.8F, -16.9813F, 22F, 1F, 32F)
				.texOffs(0, 139).addBox(-15.1972F, -36F, -10.1557F, 30F, 1F, 19F)
				.texOffs(0, 83).addBox(-9.9346F, -36F, -15.4182F, 20F, 1F, 29F)
				.texOffs(162, 139).addBox(-13.4594F, -37F, -9.0858F, 27F, 1F, 17F)
				.texOffs(366, 83).addBox(-8.7986F, -37F, -13.7466F, 18F, 1F, 26F)
				.texOffs(300, 139).addBox(-11.6822F, -37.8F, -7.9918F, 23F, 1F, 14F)
				.texOffs(292, 113).addBox(-7.6368F, -37.8F, -12.0371F, 15F, 1F, 22F)
				.texOffs(428, 139).addBox(-9.8529F, -38.48F, -6.8657F, 20F, 1F, 12F)
				.texOffs(98, 139).addBox(-6.441F, -38.48F, -10.2776F, 13F, 1F, 19F)
				.texOffs(180, 159).addBox(-7.8887F, -39.04F, -5.6564F, 16F, 1F, 10F)
				.texOffs(250, 139).addBox(-5.157F, -39.04F, -8.3882F, 10F, 1F, 15F)
				.texOffs(332, 159).addBox(-5.6309F, -39.52F, -4.2665F, 11F, 1F, 7F)
				.texOffs(54, 159).addBox(-3.681F, -39.52F, -6.2164F, 7F, 1F, 11F)
				.texOffs(116, 159).addBox(-13.6F, -22F, -21F, 27F, 6F, 5F)
				.texOffs(90, 159).addBox(-21F, -22F, -13.6F, 5F, 4F, 8F)
				.texOffs(126, 113).addBox(-22.48F, -26.2F, -12.8F, 2F, 3F, 22F)
				.texOffs(160, 171).addBox(-22.88F, -25.2F, -10.4F, 1F, 1F, 2F)
				.texOffs(160, 171).addBox(-22.88F, -25.2F, -1.6F, 1F, 1F, 2F)
				.texOffs(160, 171).addBox(-22.88F, -25.2F, 6.4F, 1F, 1F, 2F)
				.texOffs(90, 159).addBox(15.6F, -22F, -13.6F, 5F, 4F, 8F)
				.texOffs(126, 113).addBox(20.88F, -26.2F, -12.8F, 2F, 3F, 22F)
				.texOffs(160, 171).addBox(22.48F, -25.2F, -10.4F, 1F, 1F, 2F)
				.texOffs(160, 171).addBox(22.48F, -25.2F, -1.6F, 1F, 1F, 2F)
				.texOffs(160, 171).addBox(22.48F, -25.2F, 6.4F, 1F, 1F, 2F)
				.texOffs(368, 159).addBox(-5.2F, -31.6F, 19F, 10F, 7F, 1F)
				.texOffs(112, 171).addBox(-2.8F, -29.2F, 20.4F, 6F, 3F, 1F)
				.texOffs(0, 159).addBox(-8F, -39.52F, -6.4F, 16F, 1F, 11F)
				.texOffs(268, 159).addBox(-7.6F, -28F, -23F, 15F, 8F, 2F)
				.texOffs(22, 171).addBox(-7.6F, -28.2F, -23.2F, 15F, 1F, 3F)
				.texOffs(126, 171).addBox(-1.8F, -34.4F, -20.2F, 4F, 2F, 2F)
				.texOffs(366, 113).addBox(-19.2F, -22.4F, 1.8F, 1F, 21F, 2F)
				.texOffs(262, 159).addBox(-19.2F, -18.8F, -12.8F, 1F, 9F, 2F)
				.texOffs(366, 113).addBox(18.2F, -22.4F, 1.8F, 1F, 21F, 2F)
				.texOffs(262, 159).addBox(18.2F, -18.8F, -12.8F, 1F, 9F, 2F)
				.texOffs(166, 171).addBox(-19.2F, -11F, -18.8F, 38F, 1F, 1F)
				.texOffs(448, 159).addBox(-5.2F, -1.4F, 15.6F, 10F, 3F, 3F)
				.texOffs(374, 139).addBox(-19.2F, -0.6F, 3.8F, 14F, 1F, 13F)
				.texOffs(374, 139).addBox(5.2F, -0.6F, 3.8F, 14F, 1F, 13F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("helmet_c1", CubeListBuilder.create()
				.texOffs(302, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, -15.4753F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("helmet_c2", CubeListBuilder.create()
				.texOffs(302, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, 13.8753F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("helmet_c3", CubeListBuilder.create()
				.texOffs(302, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, -15.4753F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("helmet_c4", CubeListBuilder.create()
				.texOffs(302, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, 13.8753F, 0F, 0.7854F, 0F));
		PartDefinition p5 = p0.addOrReplaceChild("helmet_c5", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, -15.4225F, 0F, 0.7854F, 0F));
		PartDefinition p6 = p0.addOrReplaceChild("helmet_c6", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, 13.8225F, 0F, -0.7854F, 0F));
		PartDefinition p7 = p0.addOrReplaceChild("helmet_c7", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, -15.4225F, 0F, -0.7854F, 0F));
		PartDefinition p8 = p0.addOrReplaceChild("helmet_c8", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, 13.8225F, 0F, 0.7854F, 0F));
		PartDefinition p9 = p0.addOrReplaceChild("helmet_c9", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, -15.0464F, 0F, 0.7854F, 0F));
		PartDefinition p10 = p0.addOrReplaceChild("helmet_c10", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, 13.4464F, 0F, -0.7854F, 0F));
		PartDefinition p11 = p0.addOrReplaceChild("helmet_c11", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, -15.0464F, 0F, -0.7854F, 0F));
		PartDefinition p12 = p0.addOrReplaceChild("helmet_c12", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, 13.4464F, 0F, 0.7854F, 0F));
		PartDefinition p13 = p0.addOrReplaceChild("helmet_c13", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, -14.4097F, 0F, 0.7854F, 0F));
		PartDefinition p14 = p0.addOrReplaceChild("helmet_c14", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, 12.8097F, 0F, -0.7854F, 0F));
		PartDefinition p15 = p0.addOrReplaceChild("helmet_c15", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, -14.4097F, 0F, -0.7854F, 0F));
		PartDefinition p16 = p0.addOrReplaceChild("helmet_c16", CubeListBuilder.create()
				.texOffs(390, 159).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, 12.8097F, 0F, 0.7854F, 0F));
		PartDefinition p17 = p0.addOrReplaceChild("helmet_c17", CubeListBuilder.create()
				.texOffs(420, 159).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, -13.5591F, 0F, 0.7854F, 0F));
		PartDefinition p18 = p0.addOrReplaceChild("helmet_c18", CubeListBuilder.create()
				.texOffs(420, 159).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, 11.9591F, 0F, -0.7854F, 0F));
		PartDefinition p19 = p0.addOrReplaceChild("helmet_c19", CubeListBuilder.create()
				.texOffs(420, 159).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, -13.5591F, 0F, -0.7854F, 0F));
		PartDefinition p20 = p0.addOrReplaceChild("helmet_c20", CubeListBuilder.create()
				.texOffs(420, 159).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, 11.9591F, 0F, 0.7854F, 0F));
		PartDefinition p21 = p0.addOrReplaceChild("helmet_c21", CubeListBuilder.create()
				.texOffs(474, 159).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, -12.5416F, 0F, 0.7854F, 0F));
		PartDefinition p22 = p0.addOrReplaceChild("helmet_c22", CubeListBuilder.create()
				.texOffs(474, 159).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, 10.9416F, 0F, -0.7854F, 0F));
		PartDefinition p23 = p0.addOrReplaceChild("helmet_c23", CubeListBuilder.create()
				.texOffs(474, 159).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, -12.5416F, 0F, -0.7854F, 0F));
		PartDefinition p24 = p0.addOrReplaceChild("helmet_c24", CubeListBuilder.create()
				.texOffs(474, 159).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, 10.9416F, 0F, 0.7854F, 0F));
		PartDefinition p25 = p0.addOrReplaceChild("helmet_c25", CubeListBuilder.create()
				.texOffs(0, 171).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, -11.4006F, 0F, 0.7854F, 0F));
		PartDefinition p26 = p0.addOrReplaceChild("helmet_c26", CubeListBuilder.create()
				.texOffs(0, 171).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, 9.8006F, 0F, -0.7854F, 0F));
		PartDefinition p27 = p0.addOrReplaceChild("helmet_c27", CubeListBuilder.create()
				.texOffs(0, 171).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, -11.4006F, 0F, -0.7854F, 0F));
		PartDefinition p28 = p0.addOrReplaceChild("helmet_c28", CubeListBuilder.create()
				.texOffs(0, 171).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, 9.8006F, 0F, 0.7854F, 0F));
		PartDefinition p29 = p0.addOrReplaceChild("helmet_c29", CubeListBuilder.create()
				.texOffs(58, 171).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, -10.1803F, 0F, 0.7854F, 0F));
		PartDefinition p30 = p0.addOrReplaceChild("helmet_c30", CubeListBuilder.create()
				.texOffs(58, 171).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, 8.5803F, 0F, -0.7854F, 0F));
		PartDefinition p31 = p0.addOrReplaceChild("helmet_c31", CubeListBuilder.create()
				.texOffs(58, 171).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, -10.1803F, 0F, -0.7854F, 0F));
		PartDefinition p32 = p0.addOrReplaceChild("helmet_c32", CubeListBuilder.create()
				.texOffs(58, 171).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, 8.5803F, 0F, 0.7854F, 0F));
		PartDefinition p33 = p0.addOrReplaceChild("helmet_c33", CubeListBuilder.create()
				.texOffs(78, 171).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, -8.9324F, 0F, 0.7854F, 0F));
		PartDefinition p34 = p0.addOrReplaceChild("helmet_c34", CubeListBuilder.create()
				.texOffs(78, 171).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, 7.3324F, 0F, -0.7854F, 0F));
		PartDefinition p35 = p0.addOrReplaceChild("helmet_c35", CubeListBuilder.create()
				.texOffs(78, 171).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, -8.9324F, 0F, -0.7854F, 0F));
		PartDefinition p36 = p0.addOrReplaceChild("helmet_c36", CubeListBuilder.create()
				.texOffs(78, 171).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, 7.3324F, 0F, 0.7854F, 0F));
		PartDefinition p37 = p0.addOrReplaceChild("helmet_c37", CubeListBuilder.create()
				.texOffs(96, 171).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, -7.6479F, 0F, 0.7854F, 0F));
		PartDefinition p38 = p0.addOrReplaceChild("helmet_c38", CubeListBuilder.create()
				.texOffs(96, 171).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, 6.0479F, 0F, -0.7854F, 0F));
		PartDefinition p39 = p0.addOrReplaceChild("helmet_c39", CubeListBuilder.create()
				.texOffs(96, 171).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, -7.6479F, 0F, -0.7854F, 0F));
		PartDefinition p40 = p0.addOrReplaceChild("helmet_c40", CubeListBuilder.create()
				.texOffs(96, 171).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, 6.0479F, 0F, 0.7854F, 0F));
		PartDefinition p41 = p0.addOrReplaceChild("helmet_c41", CubeListBuilder.create()
				.texOffs(138, 171).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, -6.2687F, 0F, 0.7854F, 0F));
		PartDefinition p42 = p0.addOrReplaceChild("helmet_c42", CubeListBuilder.create()
				.texOffs(138, 171).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, 4.6687F, 0F, -0.7854F, 0F));
		PartDefinition p43 = p0.addOrReplaceChild("helmet_c43", CubeListBuilder.create()
				.texOffs(138, 171).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, -6.2687F, 0F, -0.7854F, 0F));
		PartDefinition p44 = p0.addOrReplaceChild("helmet_c44", CubeListBuilder.create()
				.texOffs(138, 171).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, 4.6687F, 0F, 0.7854F, 0F));
		PartDefinition p45 = p0.addOrReplaceChild("helmet_c45", CubeListBuilder.create()
				.texOffs(150, 171).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, -4.6833F, 0F, 0.7854F, 0F));
		PartDefinition p46 = p0.addOrReplaceChild("helmet_c46", CubeListBuilder.create()
				.texOffs(150, 171).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, 3.0833F, 0F, -0.7854F, 0F));
		PartDefinition p47 = p0.addOrReplaceChild("helmet_c47", CubeListBuilder.create()
				.texOffs(150, 171).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, -4.6833F, 0F, -0.7854F, 0F));
		PartDefinition p48 = p0.addOrReplaceChild("helmet_c48", CubeListBuilder.create()
				.texOffs(150, 171).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, 3.0833F, 0F, 0.7854F, 0F));
		PartDefinition p49 = p0.addOrReplaceChild("helmet_c49", CubeListBuilder.create()
				.texOffs(232, 159).addBox(-5.0912F, -22F, -2.6456F, 10F, 6F, 5F)
				, PartPose.offsetAndRotation(-15.5293F, 0F, -15.5293F, 0F, 0.7854F, 0F));
		PartDefinition p50 = p0.addOrReplaceChild("helmet_c50", CubeListBuilder.create()
				.texOffs(232, 159).addBox(-5.0912F, -22F, -2.6456F, 10F, 6F, 5F)
				, PartPose.offsetAndRotation(15.5293F, 0F, -15.5293F, 0F, -0.7854F, 0F));
		return LayerDefinition.create(mesh, 512, 176);
	}

	public static Map<String, String> helmet_fastPaths() {
		return Map.ofEntries(
				Map.entry("helmet", "helmet"),
				Map.entry("helmet_c1", "helmet/helmet_c1"),
				Map.entry("helmet_c2", "helmet/helmet_c2"),
				Map.entry("helmet_c3", "helmet/helmet_c3"),
				Map.entry("helmet_c4", "helmet/helmet_c4"),
				Map.entry("helmet_c5", "helmet/helmet_c5"),
				Map.entry("helmet_c6", "helmet/helmet_c6"),
				Map.entry("helmet_c7", "helmet/helmet_c7"),
				Map.entry("helmet_c8", "helmet/helmet_c8"),
				Map.entry("helmet_c9", "helmet/helmet_c9"),
				Map.entry("helmet_c10", "helmet/helmet_c10"),
				Map.entry("helmet_c11", "helmet/helmet_c11"),
				Map.entry("helmet_c12", "helmet/helmet_c12"),
				Map.entry("helmet_c13", "helmet/helmet_c13"),
				Map.entry("helmet_c14", "helmet/helmet_c14"),
				Map.entry("helmet_c15", "helmet/helmet_c15"),
				Map.entry("helmet_c16", "helmet/helmet_c16"),
				Map.entry("helmet_c17", "helmet/helmet_c17"),
				Map.entry("helmet_c18", "helmet/helmet_c18"),
				Map.entry("helmet_c19", "helmet/helmet_c19"),
				Map.entry("helmet_c20", "helmet/helmet_c20"),
				Map.entry("helmet_c21", "helmet/helmet_c21"),
				Map.entry("helmet_c22", "helmet/helmet_c22"),
				Map.entry("helmet_c23", "helmet/helmet_c23"),
				Map.entry("helmet_c24", "helmet/helmet_c24"),
				Map.entry("helmet_c25", "helmet/helmet_c25"),
				Map.entry("helmet_c26", "helmet/helmet_c26"),
				Map.entry("helmet_c27", "helmet/helmet_c27"),
				Map.entry("helmet_c28", "helmet/helmet_c28"),
				Map.entry("helmet_c29", "helmet/helmet_c29"),
				Map.entry("helmet_c30", "helmet/helmet_c30"),
				Map.entry("helmet_c31", "helmet/helmet_c31"),
				Map.entry("helmet_c32", "helmet/helmet_c32"),
				Map.entry("helmet_c33", "helmet/helmet_c33"),
				Map.entry("helmet_c34", "helmet/helmet_c34"),
				Map.entry("helmet_c35", "helmet/helmet_c35"),
				Map.entry("helmet_c36", "helmet/helmet_c36"),
				Map.entry("helmet_c37", "helmet/helmet_c37"),
				Map.entry("helmet_c38", "helmet/helmet_c38"),
				Map.entry("helmet_c39", "helmet/helmet_c39"),
				Map.entry("helmet_c40", "helmet/helmet_c40"),
				Map.entry("helmet_c41", "helmet/helmet_c41"),
				Map.entry("helmet_c42", "helmet/helmet_c42"),
				Map.entry("helmet_c43", "helmet/helmet_c43"),
				Map.entry("helmet_c44", "helmet/helmet_c44"),
				Map.entry("helmet_c45", "helmet/helmet_c45"),
				Map.entry("helmet_c46", "helmet/helmet_c46"),
				Map.entry("helmet_c47", "helmet/helmet_c47"),
				Map.entry("helmet_c48", "helmet/helmet_c48"),
				Map.entry("helmet_c49", "helmet/helmet_c49"),
				Map.entry("helmet_c50", "helmet/helmet_c50")
		);
	}

	public static LayerDefinition helmet_fast_nvg() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("helmet", CubeListBuilder.create()
				.texOffs(350, 44).addBox(-21F, -25.6F, -13.728F, 42F, 4F, 26F)
				.texOffs(0, 0).addBox(-13.728F, -25.6F, -21F, 27F, 4F, 40F)
				.texOffs(98, 83).addBox(-20.9249F, -28F, -13.6818F, 42F, 2F, 26F)
				.texOffs(134, 0).addBox(-13.6789F, -28F, -20.9277F, 27F, 2F, 40F)
				.texOffs(234, 83).addBox(-20.3892F, -30F, -13.352F, 41F, 2F, 25F)
				.texOffs(268, 0).addBox(-13.3287F, -30F, -20.4124F, 27F, 2F, 39F)
				.texOffs(0, 113).addBox(-19.4824F, -31.8F, -12.7938F, 39F, 2F, 24F)
				.texOffs(0, 44).addBox(-12.7359F, -31.8F, -19.5402F, 25F, 2F, 37F)
				.texOffs(174, 113).addBox(-18.2711F, -33.4F, -12.048F, 37F, 2F, 22F)
				.texOffs(124, 44).addBox(-11.9441F, -33.4F, -18.3751F, 24F, 2F, 35F)
				.texOffs(372, 113).addBox(-16.8221F, -34.8F, -11.156F, 34F, 1F, 21F)
				.texOffs(242, 44).addBox(-10.9969F, -34.8F, -16.9813F, 22F, 1F, 32F)
				.texOffs(0, 139).addBox(-15.1972F, -36F, -10.1557F, 30F, 1F, 19F)
				.texOffs(0, 83).addBox(-9.9346F, -36F, -15.4182F, 20F, 1F, 29F)
				.texOffs(162, 139).addBox(-13.4594F, -37F, -9.0858F, 27F, 1F, 17F)
				.texOffs(366, 83).addBox(-8.7986F, -37F, -13.7466F, 18F, 1F, 26F)
				.texOffs(370, 139).addBox(-11.6822F, -37.8F, -7.9918F, 23F, 1F, 14F)
				.texOffs(292, 113).addBox(-7.6368F, -37.8F, -12.0371F, 15F, 1F, 22F)
				.texOffs(0, 159).addBox(-9.8529F, -38.48F, -6.8657F, 20F, 1F, 12F)
				.texOffs(98, 139).addBox(-6.441F, -38.48F, -10.2776F, 13F, 1F, 19F)
				.texOffs(258, 159).addBox(-7.8887F, -39.04F, -5.6564F, 16F, 1F, 10F)
				.texOffs(320, 139).addBox(-5.157F, -39.04F, -8.3882F, 10F, 1F, 15F)
				.texOffs(476, 159).addBox(-5.6309F, -39.52F, -4.2665F, 11F, 1F, 7F)
				.texOffs(118, 159).addBox(-3.681F, -39.52F, -6.2164F, 7F, 1F, 11F)
				.texOffs(194, 159).addBox(-13.6F, -22F, -21F, 27F, 6F, 5F)
				.texOffs(154, 159).addBox(-21F, -22F, -13.6F, 5F, 4F, 8F)
				.texOffs(126, 113).addBox(-22.48F, -26.2F, -12.8F, 2F, 3F, 22F)
				.texOffs(312, 172).addBox(-22.88F, -25.2F, -10.4F, 1F, 1F, 2F)
				.texOffs(312, 172).addBox(-22.88F, -25.2F, -1.6F, 1F, 1F, 2F)
				.texOffs(312, 172).addBox(-22.88F, -25.2F, 6.4F, 1F, 1F, 2F)
				.texOffs(154, 159).addBox(15.6F, -22F, -13.6F, 5F, 4F, 8F)
				.texOffs(126, 113).addBox(20.88F, -26.2F, -12.8F, 2F, 3F, 22F)
				.texOffs(312, 172).addBox(22.48F, -25.2F, -10.4F, 1F, 1F, 2F)
				.texOffs(312, 172).addBox(22.48F, -25.2F, -1.6F, 1F, 1F, 2F)
				.texOffs(312, 172).addBox(22.48F, -25.2F, 6.4F, 1F, 1F, 2F)
				.texOffs(0, 172).addBox(-5.2F, -31.6F, 19F, 10F, 7F, 1F)
				.texOffs(264, 172).addBox(-2.8F, -29.2F, 20.4F, 6F, 3F, 1F)
				.texOffs(64, 159).addBox(-8F, -39.52F, -6.4F, 16F, 1F, 11F)
				.texOffs(346, 159).addBox(-7.6F, -28F, -23F, 15F, 8F, 2F)
				.texOffs(174, 172).addBox(-7.6F, -28.2F, -23.2F, 15F, 1F, 3F)
				.texOffs(278, 172).addBox(-1.8F, -34.4F, -20.2F, 4F, 2F, 2F)
				.texOffs(366, 113).addBox(-19.2F, -22.4F, 1.8F, 1F, 21F, 2F)
				.texOffs(340, 159).addBox(-19.2F, -18.8F, -12.8F, 1F, 9F, 2F)
				.texOffs(366, 113).addBox(18.2F, -22.4F, 1.8F, 1F, 21F, 2F)
				.texOffs(340, 159).addBox(18.2F, -18.8F, -12.8F, 1F, 9F, 2F)
				.texOffs(318, 172).addBox(-19.2F, -11F, -18.8F, 38F, 1F, 1F)
				.texOffs(102, 172).addBox(-5.2F, -1.4F, 15.6F, 10F, 3F, 3F)
				.texOffs(444, 139).addBox(-19.2F, -0.6F, 3.8F, 14F, 1F, 13F)
				.texOffs(444, 139).addBox(5.2F, -0.6F, 3.8F, 14F, 1F, 13F)
				.texOffs(458, 159).addBox(-3.2F, -30.4F, 20.4F, 6F, 6F, 3F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("helmet_c1", CubeListBuilder.create()
				.texOffs(400, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, -15.4753F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("helmet_c2", CubeListBuilder.create()
				.texOffs(400, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(-15.4753F, 0F, 13.8753F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("helmet_c3", CubeListBuilder.create()
				.texOffs(400, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, -15.4753F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("helmet_c4", CubeListBuilder.create()
				.texOffs(400, 159).addBox(-5.1421F, -25.6F, -2.671F, 10F, 4F, 5F)
				, PartPose.offsetAndRotation(15.4753F, 0F, 13.8753F, 0F, 0.7854F, 0F));
		PartDefinition p5 = p0.addOrReplaceChild("helmet_c5", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, -15.4225F, 0F, 0.7854F, 0F));
		PartDefinition p6 = p0.addOrReplaceChild("helmet_c6", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.4197F, 0F, 13.8225F, 0F, -0.7854F, 0F));
		PartDefinition p7 = p0.addOrReplaceChild("helmet_c7", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, -15.4225F, 0F, -0.7854F, 0F));
		PartDefinition p8 = p0.addOrReplaceChild("helmet_c8", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-5.1237F, -28F, -2.6618F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.4197F, 0F, 13.8225F, 0F, 0.7854F, 0F));
		PartDefinition p9 = p0.addOrReplaceChild("helmet_c9", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, -15.0464F, 0F, 0.7854F, 0F));
		PartDefinition p10 = p0.addOrReplaceChild("helmet_c10", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-15.0231F, 0F, 13.4464F, 0F, -0.7854F, 0F));
		PartDefinition p11 = p0.addOrReplaceChild("helmet_c11", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, -15.0464F, 0F, -0.7854F, 0F));
		PartDefinition p12 = p0.addOrReplaceChild("helmet_c12", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.9925F, -30F, -2.5963F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(15.0231F, 0F, 13.4464F, 0F, 0.7854F, 0F));
		PartDefinition p13 = p0.addOrReplaceChild("helmet_c13", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, -14.4097F, 0F, 0.7854F, 0F));
		PartDefinition p14 = p0.addOrReplaceChild("helmet_c14", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(-14.3519F, 0F, 12.8097F, 0F, -0.7854F, 0F));
		PartDefinition p15 = p0.addOrReplaceChild("helmet_c15", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, -14.4097F, 0F, -0.7854F, 0F));
		PartDefinition p16 = p0.addOrReplaceChild("helmet_c16", CubeListBuilder.create()
				.texOffs(22, 172).addBox(-4.7705F, -31.8F, -2.4852F, 10F, 2F, 5F)
				, PartPose.offsetAndRotation(14.3519F, 0F, 12.8097F, 0F, 0.7854F, 0F));
		PartDefinition p17 = p0.addOrReplaceChild("helmet_c17", CubeListBuilder.create()
				.texOffs(52, 172).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, -13.5591F, 0F, 0.7854F, 0F));
		PartDefinition p18 = p0.addOrReplaceChild("helmet_c18", CubeListBuilder.create()
				.texOffs(52, 172).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(-13.4551F, 0F, 11.9591F, 0F, -0.7854F, 0F));
		PartDefinition p19 = p0.addOrReplaceChild("helmet_c19", CubeListBuilder.create()
				.texOffs(52, 172).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, -13.5591F, 0F, -0.7854F, 0F));
		PartDefinition p20 = p0.addOrReplaceChild("helmet_c20", CubeListBuilder.create()
				.texOffs(52, 172).addBox(-4.4739F, -33.4F, -2.3369F, 9F, 2F, 5F)
				, PartPose.offsetAndRotation(13.4551F, 0F, 11.9591F, 0F, 0.7854F, 0F));
		PartDefinition p21 = p0.addOrReplaceChild("helmet_c21", CubeListBuilder.create()
				.texOffs(128, 172).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, -12.5416F, 0F, 0.7854F, 0F));
		PartDefinition p22 = p0.addOrReplaceChild("helmet_c22", CubeListBuilder.create()
				.texOffs(128, 172).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(-12.3825F, 0F, 10.9416F, 0F, -0.7854F, 0F));
		PartDefinition p23 = p0.addOrReplaceChild("helmet_c23", CubeListBuilder.create()
				.texOffs(128, 172).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, -12.5416F, 0F, -0.7854F, 0F));
		PartDefinition p24 = p0.addOrReplaceChild("helmet_c24", CubeListBuilder.create()
				.texOffs(128, 172).addBox(-4.1191F, -34.8F, -2.1595F, 8F, 1F, 4F)
				, PartPose.offsetAndRotation(12.3825F, 0F, 10.9416F, 0F, 0.7854F, 0F));
		PartDefinition p25 = p0.addOrReplaceChild("helmet_c25", CubeListBuilder.create()
				.texOffs(152, 172).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, -11.4006F, 0F, 0.7854F, 0F));
		PartDefinition p26 = p0.addOrReplaceChild("helmet_c26", CubeListBuilder.create()
				.texOffs(152, 172).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(-11.1795F, 0F, 9.8006F, 0F, -0.7854F, 0F));
		PartDefinition p27 = p0.addOrReplaceChild("helmet_c27", CubeListBuilder.create()
				.texOffs(152, 172).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, -11.4006F, 0F, -0.7854F, 0F));
		PartDefinition p28 = p0.addOrReplaceChild("helmet_c28", CubeListBuilder.create()
				.texOffs(152, 172).addBox(-3.7212F, -36F, -1.9606F, 7F, 1F, 4F)
				, PartPose.offsetAndRotation(11.1795F, 0F, 9.8006F, 0F, 0.7854F, 0F));
		PartDefinition p29 = p0.addOrReplaceChild("helmet_c29", CubeListBuilder.create()
				.texOffs(210, 172).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, -10.1803F, 0F, 0.7854F, 0F));
		PartDefinition p30 = p0.addOrReplaceChild("helmet_c30", CubeListBuilder.create()
				.texOffs(210, 172).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(-9.8931F, 0F, 8.5803F, 0F, -0.7854F, 0F));
		PartDefinition p31 = p0.addOrReplaceChild("helmet_c31", CubeListBuilder.create()
				.texOffs(210, 172).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, -10.1803F, 0F, -0.7854F, 0F));
		PartDefinition p32 = p0.addOrReplaceChild("helmet_c32", CubeListBuilder.create()
				.texOffs(210, 172).addBox(-3.2957F, -37F, -1.7478F, 7F, 1F, 3F)
				, PartPose.offsetAndRotation(9.8931F, 0F, 8.5803F, 0F, 0.7854F, 0F));
		PartDefinition p33 = p0.addOrReplaceChild("helmet_c33", CubeListBuilder.create()
				.texOffs(230, 172).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, -8.9324F, 0F, 0.7854F, 0F));
		PartDefinition p34 = p0.addOrReplaceChild("helmet_c34", CubeListBuilder.create()
				.texOffs(230, 172).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(-8.5774F, 0F, 7.3324F, 0F, -0.7854F, 0F));
		PartDefinition p35 = p0.addOrReplaceChild("helmet_c35", CubeListBuilder.create()
				.texOffs(230, 172).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, -8.9324F, 0F, -0.7854F, 0F));
		PartDefinition p36 = p0.addOrReplaceChild("helmet_c36", CubeListBuilder.create()
				.texOffs(230, 172).addBox(-2.8605F, -37.8F, -1.5303F, 6F, 1F, 3F)
				, PartPose.offsetAndRotation(8.5774F, 0F, 7.3324F, 0F, 0.7854F, 0F));
		PartDefinition p37 = p0.addOrReplaceChild("helmet_c37", CubeListBuilder.create()
				.texOffs(248, 172).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, -7.6479F, 0F, 0.7854F, 0F));
		PartDefinition p38 = p0.addOrReplaceChild("helmet_c38", CubeListBuilder.create()
				.texOffs(248, 172).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(-7.2233F, 0F, 6.0479F, 0F, -0.7854F, 0F));
		PartDefinition p39 = p0.addOrReplaceChild("helmet_c39", CubeListBuilder.create()
				.texOffs(248, 172).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, -7.6479F, 0F, -0.7854F, 0F));
		PartDefinition p40 = p0.addOrReplaceChild("helmet_c40", CubeListBuilder.create()
				.texOffs(248, 172).addBox(-2.4126F, -38.48F, -1.3063F, 5F, 1F, 3F)
				, PartPose.offsetAndRotation(7.2233F, 0F, 6.0479F, 0F, 0.7854F, 0F));
		PartDefinition p41 = p0.addOrReplaceChild("helmet_c41", CubeListBuilder.create()
				.texOffs(290, 172).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, -6.2687F, 0F, 0.7854F, 0F));
		PartDefinition p42 = p0.addOrReplaceChild("helmet_c42", CubeListBuilder.create()
				.texOffs(290, 172).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(-5.7692F, 0F, 4.6687F, 0F, -0.7854F, 0F));
		PartDefinition p43 = p0.addOrReplaceChild("helmet_c43", CubeListBuilder.create()
				.texOffs(290, 172).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, -6.2687F, 0F, -0.7854F, 0F));
		PartDefinition p44 = p0.addOrReplaceChild("helmet_c44", CubeListBuilder.create()
				.texOffs(290, 172).addBox(-1.9316F, -39.04F, -1.0658F, 4F, 1F, 2F)
				, PartPose.offsetAndRotation(5.7692F, 0F, 4.6687F, 0F, 0.7854F, 0F));
		PartDefinition p45 = p0.addOrReplaceChild("helmet_c45", CubeListBuilder.create()
				.texOffs(302, 172).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, -4.6833F, 0F, 0.7854F, 0F));
		PartDefinition p46 = p0.addOrReplaceChild("helmet_c46", CubeListBuilder.create()
				.texOffs(302, 172).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(-4.0978F, 0F, 3.0833F, 0F, -0.7854F, 0F));
		PartDefinition p47 = p0.addOrReplaceChild("helmet_c47", CubeListBuilder.create()
				.texOffs(302, 172).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, -4.6833F, 0F, -0.7854F, 0F));
		PartDefinition p48 = p0.addOrReplaceChild("helmet_c48", CubeListBuilder.create()
				.texOffs(302, 172).addBox(-1.3788F, -39.52F, -0.7894F, 3F, 1F, 2F)
				, PartPose.offsetAndRotation(4.0978F, 0F, 3.0833F, 0F, 0.7854F, 0F));
		PartDefinition p49 = p0.addOrReplaceChild("helmet_c49", CubeListBuilder.create()
				.texOffs(310, 159).addBox(-5.0912F, -22F, -2.6456F, 10F, 6F, 5F)
				, PartPose.offsetAndRotation(-15.5293F, 0F, -15.5293F, 0F, 0.7854F, 0F));
		PartDefinition p50 = p0.addOrReplaceChild("helmet_c50", CubeListBuilder.create()
				.texOffs(310, 159).addBox(-5.0912F, -22F, -2.6456F, 10F, 6F, 5F)
				, PartPose.offsetAndRotation(15.5293F, 0F, -15.5293F, 0F, -0.7854F, 0F));
		PartDefinition p51 = p0.addOrReplaceChild("nvg", CubeListBuilder.create()
				.texOffs(180, 159).addBox(-2.2F, -1.2F, -0.8F, 4F, 9F, 3F)
				.texOffs(430, 159).addBox(-4.8F, 7.2F, -0.2F, 10F, 5F, 4F)
				.texOffs(250, 139).addBox(-10.528F, 7.072F, -4.2F, 6F, 6F, 12F)
				.texOffs(380, 159).addBox(-11.2F, 6.4F, 5F, 8F, 8F, 2F)
				.texOffs(250, 139).addBox(4.272F, 7.072F, -4.2F, 6F, 6F, 12F)
				.texOffs(380, 159).addBox(3.6F, 6.4F, 5F, 8F, 8F, 2F)
				.texOffs(80, 172).addBox(-3.6F, 4F, 0.2F, 7F, 3F, 4F)
				, PartPose.offsetAndRotation(0F, -26.4F, 23.4F, 0F, 0F, 0F));
		PartDefinition p52 = p51.addOrReplaceChild("nvg_t1", CubeListBuilder.create()
				.texOffs(286, 139).addBox(-3.128F, -3.128F, -5.68F, 6F, 6F, 11F)
				, PartPose.offsetAndRotation(-7.4F, 10.2F, 1.6F, 0F, 0F, 0.7854F));
		PartDefinition p53 = p51.addOrReplaceChild("nvg_t2", CubeListBuilder.create()
				.texOffs(286, 139).addBox(-3.128F, -3.128F, -5.68F, 6F, 6F, 11F)
				, PartPose.offsetAndRotation(7.4F, 10.2F, 1.6F, 0F, 0F, 0.7854F));
		return LayerDefinition.create(mesh, 512, 192);
	}

	public static Map<String, String> helmet_fast_nvgPaths() {
		return Map.ofEntries(
				Map.entry("helmet", "helmet"),
				Map.entry("helmet_c1", "helmet/helmet_c1"),
				Map.entry("helmet_c2", "helmet/helmet_c2"),
				Map.entry("helmet_c3", "helmet/helmet_c3"),
				Map.entry("helmet_c4", "helmet/helmet_c4"),
				Map.entry("helmet_c5", "helmet/helmet_c5"),
				Map.entry("helmet_c6", "helmet/helmet_c6"),
				Map.entry("helmet_c7", "helmet/helmet_c7"),
				Map.entry("helmet_c8", "helmet/helmet_c8"),
				Map.entry("helmet_c9", "helmet/helmet_c9"),
				Map.entry("helmet_c10", "helmet/helmet_c10"),
				Map.entry("helmet_c11", "helmet/helmet_c11"),
				Map.entry("helmet_c12", "helmet/helmet_c12"),
				Map.entry("helmet_c13", "helmet/helmet_c13"),
				Map.entry("helmet_c14", "helmet/helmet_c14"),
				Map.entry("helmet_c15", "helmet/helmet_c15"),
				Map.entry("helmet_c16", "helmet/helmet_c16"),
				Map.entry("helmet_c17", "helmet/helmet_c17"),
				Map.entry("helmet_c18", "helmet/helmet_c18"),
				Map.entry("helmet_c19", "helmet/helmet_c19"),
				Map.entry("helmet_c20", "helmet/helmet_c20"),
				Map.entry("helmet_c21", "helmet/helmet_c21"),
				Map.entry("helmet_c22", "helmet/helmet_c22"),
				Map.entry("helmet_c23", "helmet/helmet_c23"),
				Map.entry("helmet_c24", "helmet/helmet_c24"),
				Map.entry("helmet_c25", "helmet/helmet_c25"),
				Map.entry("helmet_c26", "helmet/helmet_c26"),
				Map.entry("helmet_c27", "helmet/helmet_c27"),
				Map.entry("helmet_c28", "helmet/helmet_c28"),
				Map.entry("helmet_c29", "helmet/helmet_c29"),
				Map.entry("helmet_c30", "helmet/helmet_c30"),
				Map.entry("helmet_c31", "helmet/helmet_c31"),
				Map.entry("helmet_c32", "helmet/helmet_c32"),
				Map.entry("helmet_c33", "helmet/helmet_c33"),
				Map.entry("helmet_c34", "helmet/helmet_c34"),
				Map.entry("helmet_c35", "helmet/helmet_c35"),
				Map.entry("helmet_c36", "helmet/helmet_c36"),
				Map.entry("helmet_c37", "helmet/helmet_c37"),
				Map.entry("helmet_c38", "helmet/helmet_c38"),
				Map.entry("helmet_c39", "helmet/helmet_c39"),
				Map.entry("helmet_c40", "helmet/helmet_c40"),
				Map.entry("helmet_c41", "helmet/helmet_c41"),
				Map.entry("helmet_c42", "helmet/helmet_c42"),
				Map.entry("helmet_c43", "helmet/helmet_c43"),
				Map.entry("helmet_c44", "helmet/helmet_c44"),
				Map.entry("helmet_c45", "helmet/helmet_c45"),
				Map.entry("helmet_c46", "helmet/helmet_c46"),
				Map.entry("helmet_c47", "helmet/helmet_c47"),
				Map.entry("helmet_c48", "helmet/helmet_c48"),
				Map.entry("helmet_c49", "helmet/helmet_c49"),
				Map.entry("helmet_c50", "helmet/helmet_c50"),
				Map.entry("nvg", "helmet/nvg"),
				Map.entry("nvg_t1", "helmet/nvg/nvg_t1"),
				Map.entry("nvg_t2", "helmet/nvg/nvg_t2")
		);
	}

	public static LayerDefinition vest_pc() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("vest", CubeListBuilder.create()
				.texOffs(146, 0).addBox(-14F, 10.4F, 8.6F, 28F, 24F, 5F)
				.texOffs(268, 0).addBox(-10F, 3.6F, 8.6F, 20F, 7F, 5F)
				.texOffs(346, 0).addBox(-6.4F, 4.8F, 13.4F, 13F, 4F, 1F)
				.texOffs(80, 0).addBox(-14F, 10.4F, -13.2F, 28F, 26F, 5F)
				.texOffs(268, 0).addBox(-10F, 3.6F, -13.2F, 20F, 7F, 5F)
				.texOffs(374, 0).addBox(-4F, 3.6F, -14.4F, 8F, 3F, 1F)
				.texOffs(212, 0).addBox(-13.2F, -2F, -9.8F, 8F, 2F, 20F)
				.texOffs(326, 0).addBox(-13.2F, 0.2F, 8.6F, 8F, 4F, 2F)
				.texOffs(326, 0).addBox(-13.2F, 0.2F, -10.4F, 8F, 4F, 2F)
				.texOffs(0, 0).addBox(-17.4F, 18.4F, -9.6F, 1F, 16F, 19F)
				.texOffs(318, 0).addBox(-16.2F, 23.2F, 8.6F, 2F, 7F, 2F)
				.texOffs(212, 0).addBox(5.6F, -2F, -9.8F, 8F, 2F, 20F)
				.texOffs(326, 0).addBox(5.6F, 0.2F, 8.6F, 8F, 4F, 2F)
				.texOffs(326, 0).addBox(5.6F, 0.2F, -10.4F, 8F, 4F, 2F)
				.texOffs(40, 0).addBox(16F, 18.4F, -9.6F, 1F, 16F, 19F)
				.texOffs(318, 0).addBox(13.8F, 23.2F, 8.6F, 2F, 7F, 2F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 512, 48);
	}

	public static Map<String, String> vest_pcPaths() {
		return Map.ofEntries(
				Map.entry("vest", "vest")
		);
	}

	public static LayerDefinition vest_6b45() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("vest", CubeListBuilder.create()
				.texOffs(88, 0).addBox(-15.6F, 8.8F, 8.6F, 31F, 31F, 6F)
				.texOffs(290, 0).addBox(-11.6F, 2.4F, 8.6F, 23F, 6F, 6F)
				.texOffs(70, 45).addBox(-7.2F, 3.6F, 14.2F, 14F, 4F, 1F)
				.texOffs(162, 0).addBox(-15.6F, 8.8F, -14F, 31F, 31F, 5F)
				.texOffs(348, 0).addBox(-11.6F, 2.4F, -14F, 23F, 6F, 5F)
				.texOffs(0, 45).addBox(-10.4F, -2F, 8.6F, 21F, 5F, 3F)
				.texOffs(404, 0).addBox(-12F, -4.4F, -12.8F, 24F, 7F, 4F)
				.texOffs(234, 0).addBox(-14.4F, -3.6F, -9.6F, 9F, 4F, 19F)
				.texOffs(56, 45).addBox(-14.4F, 0.2F, 8.6F, 4F, 3F, 3F)
				.texOffs(0, 0).addBox(-17.8F, 14.4F, -10F, 2F, 25F, 20F)
				.texOffs(234, 0).addBox(5.2F, -3.6F, -9.6F, 9F, 4F, 19F)
				.texOffs(56, 45).addBox(10.4F, 0.2F, 8.6F, 4F, 3F, 3F)
				.texOffs(44, 0).addBox(16F, 14.4F, -10F, 2F, 25F, 20F)
				.texOffs(460, 0).addBox(-7.2F, 40F, 9F, 14F, 8F, 3F)
				.texOffs(48, 45).addBox(-1.6F, 6.4F, 14.2F, 3F, 6F, 1F)
				.texOffs(100, 45).addBox(-4.4F, 2.4F, -15.2F, 9F, 3F, 1F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 512, 64);
	}

	public static Map<String, String> vest_6b45Paths() {
		return Map.ofEntries(
				Map.entry("vest", "vest")
		);
	}

	public static LayerDefinition pouch_mag_mc() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-4.2F, -9.2F, 0F, 8F, 9F, 5F)
				.texOffs(56, 0).addBox(-3.8F, -12.4F, 1F, 3F, 3F, 3F)
				.texOffs(68, 0).addBox(-3.8F, -14F, 1.4F, 3F, 2F, 3F)
				.texOffs(56, 0).addBox(0.32F, -12.4F, 1F, 3F, 3F, 3F)
				.texOffs(68, 0).addBox(0.32F, -14F, 1.4F, 3F, 2F, 3F)
				.texOffs(26, 0).addBox(-4.4F, -8.2F, -0.08F, 9F, 1F, 6F)
				.texOffs(80, 0).addBox(-1.2F, -10F, 4.8F, 2F, 2F, 1F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_mag_mcPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch")
		);
	}

	public static LayerDefinition pouch_grenade_mc() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(22, 0).addBox(-3.8F, -8.4F, 1.52F, 8F, 8F, 3F)
				.texOffs(0, 0).addBox(-2.4F, -8.4F, 0.12F, 5F, 8F, 6F)
				.texOffs(50, 0).addBox(-4F, -9.8F, 0F, 8F, 1F, 6F)
				.texOffs(78, 0).addBox(-1.4F, -8.8F, 6F, 3F, 4F, 1F)
				.texOffs(90, 0).addBox(-0.88F, -11.6F, 2.2F, 2F, 2F, 2F)
				.texOffs(86, 0).addBox(0.4F, -11.6F, 3.8F, 1F, 4F, 1F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("pouch_c1", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(-2.6793F, 0F, 1.2407F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("pouch_c2", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(-2.6793F, 0F, 4.9993F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("pouch_c3", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(2.6793F, 0F, 1.2407F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("pouch_c4", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(2.6793F, 0F, 4.9993F, 0F, 0.7854F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_grenade_mcPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch"),
				Map.entry("pouch_c1", "pouch/pouch_c1"),
				Map.entry("pouch_c2", "pouch/pouch_c2"),
				Map.entry("pouch_c3", "pouch/pouch_c3"),
				Map.entry("pouch_c4", "pouch/pouch_c4")
		);
	}

	public static LayerDefinition pouch_medkit_mc() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(26, 0).addBox(-4.6F, -9.6F, 1.2F, 9F, 10F, 3F)
				.texOffs(0, 0).addBox(-3.4F, -9.6F, 0F, 7F, 10F, 6F)
				.texOffs(56, 0).addBox(-3.8F, -8.2F, 5.76F, 8F, 7F, 1F, EnumSet.of(Direction.SOUTH))
				.texOffs(74, 0).addBox(-4F, -11.4F, 1.2F, 8F, 2F, 3F)
				.texOffs(96, 0).addBox(3F, -11.4F, 2F, 2F, 2F, 2F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("pouch_c1", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(-3.6293F, 0F, 0.9707F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("pouch_c2", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(-3.6293F, 0F, 4.7893F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("pouch_c3", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(3.6293F, 0F, 0.9707F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("pouch_c4", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(3.6293F, 0F, 4.7893F, 0F, 0.7854F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_medkit_mcPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch"),
				Map.entry("pouch_c1", "pouch/pouch_c1"),
				Map.entry("pouch_c2", "pouch/pouch_c2"),
				Map.entry("pouch_c3", "pouch/pouch_c3"),
				Map.entry("pouch_c4", "pouch/pouch_c4")
		);
	}

	public static LayerDefinition pouch_radio_mc() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(4, 0).addBox(-3.8F, -10.4F, 0F, 8F, 10F, 5F)
				.texOffs(30, 0).addBox(-3F, -13F, 0.8F, 6F, 3F, 4F)
				.texOffs(82, 0).addBox(0.8F, -14.4F, 1.8F, 1F, 1F, 1F)
				.texOffs(76, 0).addBox(-2.2F, -13.8F, 1.8F, 2F, 1F, 1F)
				.texOffs(0, 0).addBox(1.12F, -30.4F, 2.12F, 1F, 16F, 1F)
				.texOffs(50, 0).addBox(-3.8F, -6.8F, -0.08F, 8F, 1F, 5F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 256, 32);
	}

	public static Map<String, String> pouch_radio_mcPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch")
		);
	}

	public static LayerDefinition pouch_mag_emr() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-4.2F, -9.2F, 0F, 8F, 9F, 5F)
				.texOffs(56, 0).addBox(-3.8F, -12.4F, 1F, 3F, 3F, 3F)
				.texOffs(68, 0).addBox(-3.8F, -14F, 1.4F, 3F, 2F, 3F)
				.texOffs(56, 0).addBox(0.32F, -12.4F, 1F, 3F, 3F, 3F)
				.texOffs(68, 0).addBox(0.32F, -14F, 1.4F, 3F, 2F, 3F)
				.texOffs(26, 0).addBox(-4.4F, -8.2F, -0.08F, 9F, 1F, 6F)
				.texOffs(80, 0).addBox(-1.2F, -10F, 4.8F, 2F, 2F, 1F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_mag_emrPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch")
		);
	}

	public static LayerDefinition pouch_grenade_emr() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(22, 0).addBox(-3.8F, -8.4F, 1.52F, 8F, 8F, 3F)
				.texOffs(0, 0).addBox(-2.4F, -8.4F, 0.12F, 5F, 8F, 6F)
				.texOffs(50, 0).addBox(-4F, -9.8F, 0F, 8F, 1F, 6F)
				.texOffs(78, 0).addBox(-1.4F, -8.8F, 6F, 3F, 4F, 1F)
				.texOffs(90, 0).addBox(-0.88F, -11.6F, 2.2F, 2F, 2F, 2F)
				.texOffs(86, 0).addBox(0.4F, -11.6F, 3.8F, 1F, 4F, 1F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("pouch_c1", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(-2.6793F, 0F, 1.2407F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("pouch_c2", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(-2.6793F, 0F, 4.9993F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("pouch_c3", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(2.6793F, 0F, 1.2407F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("pouch_c4", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-0.9899F, -8.4F, -0.595F, 2F, 8F, 1F)
				, PartPose.offsetAndRotation(2.6793F, 0F, 4.9993F, 0F, 0.7854F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_grenade_emrPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch"),
				Map.entry("pouch_c1", "pouch/pouch_c1"),
				Map.entry("pouch_c2", "pouch/pouch_c2"),
				Map.entry("pouch_c3", "pouch/pouch_c3"),
				Map.entry("pouch_c4", "pouch/pouch_c4")
		);
	}

	public static LayerDefinition pouch_medkit_emr() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(26, 0).addBox(-4.6F, -9.6F, 1.2F, 9F, 10F, 3F)
				.texOffs(0, 0).addBox(-3.4F, -9.6F, 0F, 7F, 10F, 6F)
				.texOffs(56, 0).addBox(-3.8F, -8.2F, 5.76F, 8F, 7F, 1F, EnumSet.of(Direction.SOUTH))
				.texOffs(74, 0).addBox(-4F, -11.4F, 1.2F, 8F, 2F, 3F)
				.texOffs(96, 0).addBox(3F, -11.4F, 2F, 2F, 2F, 2F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		PartDefinition p1 = p0.addOrReplaceChild("pouch_c1", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(-3.6293F, 0F, 0.9707F, 0F, 0.7854F, 0F));
		PartDefinition p2 = p0.addOrReplaceChild("pouch_c2", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(-3.6293F, 0F, 4.7893F, 0F, -0.7854F, 0F));
		PartDefinition p3 = p0.addOrReplaceChild("pouch_c3", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(3.6293F, 0F, 0.9707F, 0F, -0.7854F, 0F));
		PartDefinition p4 = p0.addOrReplaceChild("pouch_c4", CubeListBuilder.create()
				.texOffs(50, 0).addBox(-0.8485F, -9.6F, -0.5243F, 2F, 10F, 1F)
				, PartPose.offsetAndRotation(3.6293F, 0F, 4.7893F, 0F, 0.7854F, 0F));
		return LayerDefinition.create(mesh, 256, 16);
	}

	public static Map<String, String> pouch_medkit_emrPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch"),
				Map.entry("pouch_c1", "pouch/pouch_c1"),
				Map.entry("pouch_c2", "pouch/pouch_c2"),
				Map.entry("pouch_c3", "pouch/pouch_c3"),
				Map.entry("pouch_c4", "pouch/pouch_c4")
		);
	}

	public static LayerDefinition pouch_radio_emr() {
		MeshDefinition mesh = new MeshDefinition();
		PartDefinition root = mesh.getRoot();
		PartDefinition p0 = root.addOrReplaceChild("pouch", CubeListBuilder.create()
				.texOffs(4, 0).addBox(-3.8F, -10.4F, 0F, 8F, 10F, 5F)
				.texOffs(30, 0).addBox(-3F, -13F, 0.8F, 6F, 3F, 4F)
				.texOffs(82, 0).addBox(0.8F, -14.4F, 1.8F, 1F, 1F, 1F)
				.texOffs(76, 0).addBox(-2.2F, -13.8F, 1.8F, 2F, 1F, 1F)
				.texOffs(0, 0).addBox(1.12F, -30.4F, 2.12F, 1F, 16F, 1F)
				.texOffs(50, 0).addBox(-3.8F, -6.8F, -0.08F, 8F, 1F, 5F)
				, PartPose.offsetAndRotation(0F, 0F, 0F, 0F, 0F, 0F));
		return LayerDefinition.create(mesh, 256, 32);
	}

	public static Map<String, String> pouch_radio_emrPaths() {
		return Map.ofEntries(
				Map.entry("pouch", "pouch")
		);
	}
}
